// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contactDeliverability = `-- name: ContactDeliverability :one
SELECT count(*)::int                                         AS accepted,
       count(*) FILTER (WHERE delivery_status = 'sent')::int AS delivered
  FROM contact_messages
 WHERE received_at > now() - $1::interval
`

type ContactDeliverabilityRow struct {
	Accepted  int32
	Delivered int32
}

// ContactDeliverability is the fifth SLI, and the only one this database can
// answer on its own. docs/slo.md holds the definition; this is the query it has
// been waiting for since F5, and issue #206 is the reason it took this long —
// the shape of the answer was a contract decision before it was a SELECT.
//
// ONE ROW, ALWAYS, and for HealthCounts' reason above: count() over no rows is
// zero, not no row. "Nobody has written yet" is therefore an answer and never a
// pgx.ErrNoRows the caller has to translate.
//
// TWO COUNTS AND NOT THE QUOTIENT, which is a departure from metrics.sql, and
// the reason is the generator rather than taste. Written as a CASE that answers
// NULL for an empty window, sqlc types the column `interface{}`; given an outer
// ::double precision cast it types it a plain `float64`, which is worse — the
// scan would then fail on precisely the empty database, the one case the null
// branch exists for. Both counts are NOT NULL and infer exactly, so the division
// and its null branch live in internal/health, where a test reaches them without
// Postgres. InsertMetricSnapshot keeps its CASE because uptime is a sum over
// another table; here numerator and denominator both reach the answer anyway,
// and a quotient beside them would be the same fact stated twice.
//
// 'sent' IN THE NUMERATOR, EVERYTHING IN THE DENOMINATOR. A row still 'queued'
// has not been delivered, so it lowers the rate until it lands — at most the
// dispatcher's last retry away (0·2·6·14·30 minutes, internal/contact/policy.go).
// That is the direction worth having: a queue that jams is visible while it is
// jammed rather than half an hour later. Both counts reach the answer so that a
// reader can tell that dip from a real loss, which at a single-digit denominator
// is the whole difference between the two.
//
// NO INDEX FOR THIS SCAN, and that is 00006_contact.sql's own rule: the
// received_at index arrives "with the job, not before it". This table grows with
// submissions rather than with measurements, and `accepted` in this very answer
// is the instrument that will say when the scan has earned one.
//
// The window is an argument for the reason InsertMetricSnapshot's is: thirty is
// written in exactly one place, and the answer carries it so that no page has to
// assume it.
func (q *Queries) ContactDeliverability(ctx context.Context, windowSize pgtype.Interval) (ContactDeliverabilityRow, error) {
	row := q.db.QueryRow(ctx, contactDeliverability, windowSize)
	var i ContactDeliverabilityRow
	err := row.Scan(&i.Accepted, &i.Delivered)
	return i, err
}

const healthCounts = `-- name: HealthCounts :one

SELECT
    (SELECT count(*) FROM systems WHERE state = 'live')::int AS systems_live,
    (SELECT count(*) FROM systems)::int                      AS systems_total
`

type HealthCountsRow struct {
	SystemsLive  int32
	SystemsTotal int32
}

// The queries behind GET /api/health.
//
// Five of them rather than one clever join, and that is a decision. It was three
// in C2, and the reason has held twice since. A single LEFT JOIN would save four
// round trips on an endpoint whose answer is cached for sixty seconds — and it
// would hand sqlc a set of columns whose nullability it cannot infer:
// `deploys.sha` is NOT NULL in the table, so a left-joined `sha` is generated
// as a plain string, and the first health check on a database with no deploys
// would fail scanning NULL into it. The generator would be right about the
// schema and wrong about the query.
//
// Split, every column carries the nullability it has in its own table, and
// "there is no row" arrives as pgx.ErrNoRows — which is the honest shape for
// "nothing has been measured yet". Invariant 1 has somewhere to point.
//
// ContactDeliverability at the bottom is the fifth, and it makes the same
// argument from the other side: two count()s infer exactly, and the one column
// that would have needed inferring was moved into Go rather than guessed at.
// HealthCounts always returns exactly one row, including on an empty database:
// count() over no rows is zero, not no row. These two numbers are the only part
// of the health answer that is never null, which is why they are the part that
// decides between an answer and a 500.
func (q *Queries) HealthCounts(ctx context.Context) (HealthCountsRow, error) {
	row := q.db.QueryRow(ctx, healthCounts)
	var i HealthCountsRow
	err := row.Scan(&i.SystemsLive, &i.SystemsTotal)
	return i, err
}

const lastDeploy = `-- name: LastDeploy :one
SELECT d.sha, d.duration_sec, d.result, d.deployed_at
  FROM deploys d
  JOIN systems s ON s.id = d.system_id
 WHERE s.slug = $1
 ORDER BY d.deployed_at DESC
 LIMIT 1
`

type LastDeployRow struct {
	Sha         string
	DurationSec int32
	Result      string
	DeployedAt  pgtype.Timestamptz
}

// LastDeploy serves OpsSummary.lastDeploy. deploys_by_system_time_idx exists
// for exactly this query; its comment in 00004_operations.sql says so.
func (q *Queries) LastDeploy(ctx context.Context, slug string) (LastDeployRow, error) {
	row := q.db.QueryRow(ctx, lastDeploy, slug)
	var i LastDeployRow
	err := row.Scan(
		&i.Sha,
		&i.DurationSec,
		&i.Result,
		&i.DeployedAt,
	)
	return i, err
}

const latestMetrics = `-- name: LatestMetrics :one
SELECT m.uptime_90d, m.p95_ms, m.error_rate, m.measured_at
  FROM metric_snapshots m
  JOIN systems s ON s.id = m.system_id
 WHERE s.slug = $1
   AND s.state = 'live'
 ORDER BY m.measured_at DESC
 LIMIT 1
`

type LatestMetricsRow struct {
	Uptime90d  *float64
	P95Ms      *float64
	ErrorRate  *float64
	MeasuredAt pgtype.Timestamptz
}

// LatestMetrics carries invariant 3 in its WHERE clause: metrics exist only for
// a system that is live. Written here rather than in Go, so that a system
// leaving 'live' empties its own metrics without anyone remembering to.
//
// Reads backwards along metric_snapshots_unique_instant (system_id,
// measured_at) — the shape 00005_metrics.sql measured that index against.
func (q *Queries) LatestMetrics(ctx context.Context, slug string) (LatestMetricsRow, error) {
	row := q.db.QueryRow(ctx, latestMetrics, slug)
	var i LatestMetricsRow
	err := row.Scan(
		&i.Uptime90d,
		&i.P95Ms,
		&i.ErrorRate,
		&i.MeasuredAt,
	)
	return i, err
}

const selfState = `-- name: SelfState :one
SELECT state FROM systems WHERE slug = $1
`

// SelfState is its own query rather than a scalar subquery on the one above.
// As a subquery it would be NULL for a slug that does not exist, and sqlc reads
// the nullability off systems.state, which is NOT NULL — so it would generate a
// plain string and the scan would fail on exactly the case the query exists to
// detect. Separate, "no such system" is pgx.ErrNoRows, which is a shape the
// caller can act on.
func (q *Queries) SelfState(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRow(ctx, selfState, slug)
	var state string
	err := row.Scan(&state)
	return state, err
}
