// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// The only table with personal data, and the only one the public API never reads.
type ContactMessage struct {
	ID               string
	ReceivedAt       pgtype.Timestamptz
	ClientTs         pgtype.Timestamptz
	Name             string
	Email            string
	Message          string
	MessageHash      []byte
	IpHash           []byte
	DwellMs          int32
	DeliveryStatus   string
	DeliveryAttempts int32
	DeliveredAt      pgtype.Timestamptz
	LastError        *string
	MailMessageID    *string
}

// The last good GitHub calendar. The only table here that may be truncated without loss.
type ContributionsCache struct {
	Login              string
	TotalContributions int32
	Weeks              []byte
	FetchedAt          pgtype.Timestamptz
}

type Deploy struct {
	ID          int64
	SystemID    int64
	Sha         string
	DurationSec int32
	Result      string
	DeployedAt  pgtype.Timestamptz
	RecordedAt  pgtype.Timestamptz
}

type Incident struct {
	ID          string
	SystemID    int64
	StartedAt   pgtype.Timestamptz
	DurationSec int32
	Cause       string
	Fix         string
	PostSlug    string
	CreatedAt   pgtype.Timestamptz
}

// Nullable by design (invariant 1). Invariant 3 is enforced on the read path in C2.
type MetricSnapshot struct {
	ID         int64
	SystemID   int64
	MeasuredAt pgtype.Timestamptz
	Uptime90d  *float64
	P95Ms      *float64
	ErrorRate  *float64
	RecordedAt pgtype.Timestamptz
}

type Module struct {
	ID        int64
	ModuleNo  string
	Title     string
	CreatedAt pgtype.Timestamptz
}

type OpsCheck struct {
	ID         int64
	SystemID   int64
	ObservedAt pgtype.Timestamptz
	RecordedAt pgtype.Timestamptz
	Up         bool
	LatencyMs  *int32
	Reason     *string
	Origin     string
	SourceRef  *string
}

// Daily roll-up of ops_checks. checks_total = 0 is nodata, enforced both ways.
type OpsDay struct {
	SystemID    int64
	Day         pgtype.Date
	State       string
	DownSec     int32
	ChecksTotal int32
	ChecksUp    int32
	IncidentID  *string
	ComputedAt  pgtype.Timestamptz
}

// One row per system this site tracks. No metric columns: see metric_snapshots.
type System struct {
	ID           int64
	Slug         string
	SystemNo     string
	Name         string
	State        string
	SourceAccess string
	SourceUrl    *string
	SourceReason *string
	Stack        []string
	CreatedAt    pgtype.Timestamptz
}

// No state column, by design. States are derived in v_track_states (B3, ADR 0003).
type Track struct {
	ID        int64
	ModuleID  int64
	Name      string
	SortOrder int16
	CreatedAt pgtype.Timestamptz
}

type TrackEvidence struct {
	ID        int64
	TrackID   int64
	SystemID  int64
	Detail    *string
	CreatedAt pgtype.Timestamptz
}

// Derived track states. There is no tracks.state column, by design (ADR 0003).
type VTrackState struct {
	TrackID         int64
	LiveSystems     int64
	BuildingSystems int64
	State           string
}
