// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ops.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backfillOpsChecks = `-- name: BackfillOpsChecks :execrows
INSERT INTO ops_checks (system_id, observed_at, up, reason, origin, source_ref)
SELECT
    $1,
    o.observed_at,
    false,
    $2,
    'backfill',
    $3
FROM unnest($4::timestamptz[]) AS o (observed_at)
ORDER BY o.observed_at
ON CONFLICT (system_id, observed_at) DO NOTHING
`

type BackfillOpsChecksParams struct {
	SystemID   int64
	Reason     *string
	SourceRef  *string
	ObservedAt []pgtype.Timestamptz
}

// BackfillOpsChecks replays the outages this host could not record about itself.
//
// The other half of the sentence InsertOpsCheck above starts. That one is the
// live prober and writes origin='probe'; this one is F4's replay of
// uptime-log.txt from the ops-data branch, and every column that could carry a
// claim is a constant here rather than an argument:
//
//	up          is false, always. The file is an OUTAGE log. "The site was up"
//	            is witnessed by a live probe or by nobody at all, and a replayed
//	            line must not be able to say it (ADR 0038).
//	latency_ms  is left out of the column list, so it is NULL. There is no
//	            measurement to report from a request that never completed, and
//	            ops_checks_no_latency_when_down_ck is satisfied by construction
//	            rather than by the caller remembering.
//	origin      is 'backfill', so the grid can tell a measurement from a
//	            reconstruction without asking anybody's word for it.
//
// source_ref IS an argument, and it is the one this table's CHECK insists on:
// the commit on ops-data the lines were read from. That is what makes a derived
// row traceable to something a stranger can fetch and count for themselves.
//
// ONE STATEMENT PER OUTAGE, not per instant and not per file. An outage of a day
// is 288 rows, and 288 round trips through the pool during startup is a cost with
// nothing to show for it; unnest turns the instants into rows in one pass. The
// outage is also the unit that shares a reason, which is why reason is a scalar
// here — a shape that carried one reason per row would have to promise that the
// two arrays stay the same length, and Postgres answers a mismatch with NULLs
// rather than with an error.
//
// ORDER BY is not decoration. ADR 0035 runs two instances of this binary during
// a rollout and both start their backfill; RollUpOpsDays already sorts before
// its ON CONFLICT so that two writers take the same rows in the same order, and
// this statement wants the same protection from the same deadlock.
//
// ON CONFLICT DO NOTHING is what makes re-reading the file free — the loop reads
// it again after every restart — and it is also the rule "a backfill never
// overwrites a live probe", enforced rather than promised. The caller counts the
// affected rows so the discarded ones are visible in the log.
func (q *Queries) BackfillOpsChecks(ctx context.Context, arg BackfillOpsChecksParams) (int64, error) {
	result, err := q.db.Exec(ctx, backfillOpsChecks,
		arg.SystemID,
		arg.Reason,
		arg.SourceRef,
		arg.ObservedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDeploy = `-- name: InsertDeploy :execrows
INSERT INTO deploys (system_id, sha, duration_sec, result, deployed_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (system_id, sha, deployed_at) DO NOTHING
`

type InsertDeployParams struct {
	SystemID    int64
	Sha         string
	DurationSec int32
	Result      string
	DeployedAt  pgtype.Timestamptz
}

// InsertDeploy records what the pipeline says its own release cost.
//
// The unique constraint is (system_id, sha, deployed_at) and the migration says
// why in one line: "a retried POST /api/internal/deploy must not produce a
// second bar". Two genuinely separate deploys of the same commit — a rollback
// and the redeploy after it — differ in deployed_at and are two rows, which is
// correct: they are two events.
func (q *Queries) InsertDeploy(ctx context.Context, arg InsertDeployParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDeploy,
		arg.SystemID,
		arg.Sha,
		arg.DurationSec,
		arg.Result,
		arg.DeployedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOpsCheck = `-- name: InsertOpsCheck :execrows
INSERT INTO ops_checks (system_id, observed_at, up, latency_ms, reason, origin)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'probe'
)
ON CONFLICT (system_id, observed_at) DO NOTHING
`

type InsertOpsCheckParams struct {
	SystemID   int64
	ObservedAt pgtype.Timestamptz
	Up         bool
	LatencyMs  *int32
	Reason     *string
}

// InsertOpsCheck records one external observation of this host.
//
// origin is fixed to 'probe' here rather than taken from the caller. The other
// value the CHECK allows is 'backfill', which belongs to F4's replay of
// uptime-log.txt and carries a source_ref naming the commit; letting an HTTP
// body choose between them would let a live probe claim to be evidence from
// outside the infrastructure, which is the one claim this table exists to make
// honestly.
//
// recorded_at is NOT set, deliberately. Its default is now(), and now() is what
// RollUpOpsDays scans on — a recorded_at supplied by the caller could put a new
// row outside the loop's lookback window and make it invisible for ever, while
// observed_at stays free to be as old as the observation really is.
//
// ON CONFLICT DO NOTHING against ops_checks_unique_observation makes a retry
// free: a prober that times out waiting for our 204 may send the same
// observation again without producing a second one. It also means a second
// report for the same instant is DISCARDED rather than applied, including one
// that disagrees about `up`. That is the migration's own rule — "a backfill
// never overwrites a live probe" — and the caller counts the affected rows so
// the discard is at least visible in the log.
func (q *Queries) InsertOpsCheck(ctx context.Context, arg InsertOpsCheckParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertOpsCheck,
		arg.SystemID,
		arg.ObservedAt,
		arg.Up,
		arg.LatencyMs,
		arg.Reason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rollUpOpsDays = `-- name: RollUpOpsDays :execrows

WITH touched AS (
    SELECT DISTINCT
           c.system_id,
           (c.observed_at AT TIME ZONE 'UTC')::date AS day
      FROM ops_checks c
     WHERE c.recorded_at >= now() - ($3::int * interval '1 second')
),
rolled AS (
    SELECT t.system_id,
           t.day,
           a.checks_total,
           a.checks_up,
           a.checks_down
      FROM touched t
      CROSS JOIN LATERAL (
          SELECT count(*)                         AS checks_total,
                 count(*) FILTER (WHERE c.up)     AS checks_up,
                 count(*) FILTER (WHERE NOT c.up) AS checks_down
            FROM ops_checks c
           WHERE c.system_id = t.system_id
             AND c.observed_at >= (t.day::timestamp AT TIME ZONE 'UTC')
             AND c.observed_at <  ((t.day + 1)::timestamp AT TIME ZONE 'UTC')
      ) a
)
INSERT INTO ops_days (system_id, day, state, down_sec, checks_total, checks_up, computed_at)
SELECT system_id,
       day,
       CASE
           WHEN checks_down = 0                            THEN 'ok'
           WHEN checks_down < $1::int THEN 'degraded'
           ELSE                                                 'outage'
       END,
       LEAST(checks_down * $2::int, 86400)::int,
       checks_total,
       checks_up,
       now()
  FROM rolled
 ORDER BY system_id, day
    ON CONFLICT (system_id, day) DO UPDATE SET
       state        = EXCLUDED.state,
       down_sec     = EXCLUDED.down_sec,
       checks_total = EXCLUDED.checks_total,
       checks_up    = EXCLUDED.checks_up,
       computed_at  = EXCLUDED.computed_at
`

type RollUpOpsDaysParams struct {
	OutageChecks     int32
	ProbeIntervalSec int32
	LookbackSec      int32
}

// The aggregation behind the operations grid: ops_checks -> ops_days.
//
// One statement, and the whole of C4's arithmetic is in it. ADR 0017 put the
// 91-day window in SQL so the read path could not invent an `ok`; this is the
// other half of the same decision. The write path cannot invent one either,
// because a day with no check never reaches the INSERT at all.
//
// Today is (now() AT TIME ZONE 'UTC')::date everywhere in this file, never
// current_date, for the reason systems.sql gives at the top: ops_days.day is a
// UTC date, day-one.sql builds its grid in UTC, and two definitions of "today"
// is one too many for a site whose whole claim is that the numbers can be
// recounted.
// RollUpOpsDays recomputes every day that has received a raw check recently.
//
// Three parameters and no defaults, so the caller states the probe cadence, the
// outage threshold and the scan bound. The db test can therefore replay the
// Incident fixture's own convention (1800 s, 2 checks) and get its stated
// histogram back; a rule baked into this file would make that test a tautology.
//
// WHY A DAY WITHOUT A MEASUREMENT CANNOT COME OUT `ok`. `rolled` is an inner
// join against ops_checks, so a group exists only where at least one check does.
// The CASE has no 'nodata' branch and needs none: an unmeasured day produces no
// row here in any state. The gap is made by the read path — generate_series plus
// COALESCE(o.state, 'nodata') in OpsDaysForSystem — not remembered by this one.
// That is invariant 6 as a property of the shape rather than as a rule somebody
// has to keep. ops_days_nodata_iff_unmeasured_ck (00004_operations.sql) stays as
// the guard against a later edit of the CASE above; it is tested directly in
// migrations/invariants_db_test.go and is not this query's business.
//
// TWO WINDOWS, TWO COLUMNS. `touched` is bounded on recorded_at — what the
// database has newly learned — and `rolled` groups on observed_at — which day it
// happened. That is exactly the pair 00004_operations.sql describes, and it is
// what makes the F4 backfill free: a line replayed from uptime-log.txt carries a
// months-old observed_at and a recorded_at of now(), so it is inside the scan
// however old the observation is.
//
// `rolled` re-reads the FULL day, not only the rows the scan just found. A
// roll-up over a slice of a day would undercount checks_total and put a wrong
// number underneath a correct-looking colour.
//
// The second stage is a LATERAL and the predicate is a half-open range on
// observed_at, and both halves of that were measured rather than assumed.
//
// The range, first: (observed_at AT TIME ZONE 'UTC')::date = t.day is not
// sargable and throws away ops_checks_unique_observation. The range is the shape
// 00004_operations.sql names as "what the aggregation reads", and one day out of
// 52 416 rows comes back through the index in 0.27 ms.
//
// The LATERAL, second, and it is the same lesson ListSystems learned in C2. As a
// plain join the planner merge-joins on system_id alone and drops 4.7 million
// rows by filter — 1.63 s for 182 days. The LATERAL forces one index lookup per
// touched day instead, and the same work takes 51 ms. The measurement is in
// docs/runbooks/migrations.md; it was never the index, it was the question.
//
// ORDER BY before ON CONFLICT is not cosmetic. E5 runs two instances of this
// binary at once during a deploy, and two upserts touching the same rows in
// different orders is the textbook deadlock.
//
// LEAST is load-bearing: ops_days_down_sec_ck caps down_sec at a full day, so
// without it a misconfigured cadence would abort the whole statement instead of
// clamping one cell.
//
// incident_id is deliberately absent from the DO UPDATE list. The notch is
// human-curated — 00004_operations.sql says C4 aggregates the outage and a
// person writes the post-mortem afterwards — so recomputing a day must not
// touch it.
func (q *Queries) RollUpOpsDays(ctx context.Context, arg RollUpOpsDaysParams) (int64, error) {
	result, err := q.db.Exec(ctx, rollUpOpsDays, arg.OutageChecks, arg.ProbeIntervalSec, arg.LookbackSec)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const systemIDBySlug = `-- name: SystemIDBySlug :one

SELECT id FROM systems WHERE slug = $1
`

// The write side of the grid: the two rows C7's internal endpoints append.
//
// Neither aggregates anything. The probe adds one raw observation and the loop
// in internal/ops finds it on the next tick — ADR 0019 already decided that,
// and it is why C7 is small.
// SystemIDBySlug resolves the one system both internal endpoints write against.
//
// Separate from the two inserts below, and that is the decision worth the extra
// round trip. Folded in as `INSERT ... SELECT id FROM systems WHERE slug = $1
// ... ON CONFLICT DO NOTHING`, zero affected rows would mean two different
// things — "no such system", which is a misconfiguration and a 500, and "that
// observation is already recorded", which is a 204. One return value carrying
// two states is the kind of economy that comes back later as a ghost.
//
// pgx.ErrNoRows is therefore load-bearing: it is the only way the caller learns
// that SITE_SYSTEM_SLUG names nothing.
func (q *Queries) SystemIDBySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRow(ctx, systemIDBySlug, slug)
	var id int64
	err := row.Scan(&id)
	return id, err
}
