// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training.sql

package store

import (
	"context"
)

const listModules = `-- name: ListModules :many

SELECT module_no, title
  FROM modules
 ORDER BY module_no
`

type ListModulesRow struct {
	ModuleNo string
	Title    string
}

// The queries behind GET /api/training.
//
// Three of them, and none joins the whole tree. A single
// `tracks LEFT JOIN track_evidence LEFT JOIN systems` would be the obvious shape
// and it is the trap ADR 0016 describes, at its worst spot: nine of the
// twenty-two tracks have no evidence at all, so `systems.slug` and
// `systems.system_no` arrive NULL — both NOT NULL in their own table, so sqlc
// generates plain `string` and the scan fails on exactly the rows this endpoint
// exists to show. The nine self-study lines are the honest half of the training
// log; a query that cannot carry them is the wrong query.
//
// Split, every column keeps the nullability it has in its own table, and the
// handler joins the three answers by track id — an integer that never leaves the
// process, because the contract exposes no track id.
//
// The ORDER BY clauses are part of the answer, not a convenience. Module order
// and sort_order are the order of the design sheet, and a stable row order is
// what makes the ETag stable: two identical database states have to produce the
// same tag, or the 304 path is dead code that nobody notices.
// ListModules is its own query rather than a set of columns on the one below,
// and the reason is a module with no tracks. Joined, it would vanish; separate,
// it comes back with `tracks: []`. The seed has no such module and `make seed`
// can produce one, and "the module is empty" is a different statement from "the
// module does not exist".
func (q *Queries) ListModules(ctx context.Context) ([]ListModulesRow, error) {
	rows, err := q.db.Query(ctx, listModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModulesRow{}
	for rows.Next() {
		var i ListModulesRow
		if err := rows.Scan(&i.ModuleNo, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackEvidence = `-- name: ListTrackEvidence :many
SELECT e.track_id, s.slug, s.system_no, e.detail
  FROM track_evidence e
  JOIN systems s ON s.id = e.system_id
 ORDER BY e.track_id, s.system_no
`

type ListTrackEvidenceRow struct {
	TrackID  int64
	Slug     string
	SystemNo string
	Detail   *string
}

// ListTrackEvidence is the "SHIPPED IN → 02 TIMSEIL.DEV (BUILD + DEPLOY)" line,
// in the lowercase the API speaks. Inner join, and safe: track_evidence.system_id
// is NOT NULL with ON DELETE RESTRICT (invariant 5), so every row here has a
// system and no evidence line can point into a gap.
//
// detail is the only nullable column and is nullable in its own table, so it
// arrives as *string without help — the parenthesis is either absent or it says
// something (00003_training.sql).
//
// Ordered by system_no inside a track so that a track proven by two systems
// always lists them the same way round.
func (q *Queries) ListTrackEvidence(ctx context.Context) ([]ListTrackEvidenceRow, error) {
	rows, err := q.db.Query(ctx, listTrackEvidence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackEvidenceRow{}
	for rows.Next() {
		var i ListTrackEvidenceRow
		if err := rows.Scan(
			&i.TrackID,
			&i.Slug,
			&i.SystemNo,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksWithState = `-- name: ListTracksWithState :many
SELECT m.module_no, t.id AS track_id, t.name, v.state
  FROM tracks t
  JOIN modules m        ON m.id = t.module_id
  JOIN v_track_states v ON v.track_id = t.id
 ORDER BY m.module_no, t.sort_order
`

type ListTracksWithStateRow struct {
	ModuleNo string
	TrackID  int64
	Name     string
	State    string
}

// ListTracksWithState reads the derivation rather than repeating it. Invariant 2
// lives in v_track_states (ADR 0003) and nowhere else — no Go code decides
// between core, applied, learning and queued, it only carries what this query
// returns.
//
// JOIN, not LEFT JOIN: the view groups over `tracks`, so it has exactly one row
// per track by construction. A LEFT JOIN would hide that guarantee and hand sqlc
// a nullable `state` for a column that cannot be missing.
//
// track_id is selected for the handler alone. It is how the evidence rows below
// find their track; it never reaches the response, because the contract has no
// field for it.
func (q *Queries) ListTracksWithState(ctx context.Context) ([]ListTracksWithStateRow, error) {
	rows, err := q.db.Query(ctx, listTracksWithState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTracksWithStateRow{}
	for rows.Next() {
		var i ListTracksWithStateRow
		if err := rows.Scan(
			&i.ModuleNo,
			&i.TrackID,
			&i.Name,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
