//go:build db

// Phase B3's acceptance criterion: a thousand generated evidence
// constellations, and both sides agree on every one of them.
//
// The two sides are v_track_states (00007) and skillState() in
// docs/design/code/tokens.ts. ADR 0003 makes the view the truth and the
// reference a rendering aid — but a reference nobody checks is a second truth
// waiting to drift, so it gets checked. The TypeScript answer arrives as
// testdata/skill_states.json, generated by tools/gen-skill-states.mjs, because
// this test runs in a container that has Go and nothing else.
//
// A third party joins in: httpx.TrackState, generated from the contract. With
// it, one assertion holds SQL, TypeScript and OpenAPI against each other.
//
// Run with: make check-db
package migrations_test

import (
	"database/sql"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"
	"testing"

	"pgregory.net/rapid"

	"github.com/G1NG4R/timseil-dev/api/internal/httpx"
)

// The acceptance criterion is a number, so it belongs in the code and not in an
// invocation: `go test -tags=db ./...` runs a thousand cases whether or not
// anybody remembered a flag. rapid registers these flags in its own init, and an
// imported package is initialised before the importing one, so they exist by
// now; the command line still wins, because flag.Parse runs later, inside m.Run.
//
// nofailfile carries more weight than it looks. On a failure rapid writes
// testdata/rapid/*.fail next to the test — and this test runs in a container as
// root over the bind mount, which is exactly how phase A4 ended up with
// root-owned web/.next and api/tmp that the owner could not delete. The seed in
// the failure output reproduces the case without leaving anything behind.
func init() {
	for name, value := range map[string]string{
		"rapid.checks":     "1000",
		"rapid.nofailfile": "true",
	} {
		if err := flag.Set(name, value); err != nil {
			panic("setting " + name + ": " + err.Error())
		}
	}
}

// ------------------------------------------------------------------ reference

type skillState struct {
	LiveSystems     int    `json:"liveSystems"`
	BuildingSystems int    `json:"buildingSystems"`
	UI              string `json:"ui"`
	API             string `json:"api"`
}

type counts struct{ live, building int }

// The helpers below serve both *testing.T and *rapid.T. rapid.T deliberately
// does not implement testing.TB — testing.TB is sealed — and it has no Helper(),
// so these two interfaces are the common ground: report a failure, run a
// statement. No t.Helper() in the shared helpers for the same reason; the
// message carries the context instead of the line number.
type failer interface {
	Fatalf(format string, args ...any)
}

type querier interface {
	QueryRow(query string, args ...any) *sql.Row
	Exec(query string, args ...any) (sql.Result, error)
}

// loadSkillStates reads the generated truth table. A missing or short file is
// fatal: the point of this test is the comparison, and a comparison against
// nothing is the green nothing this repository is built to avoid.
func loadSkillStates(t *testing.T) map[counts]skillState {
	t.Helper()

	const path = "testdata/skill_states.json"
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s — run make gen: %v", path, err)
	}

	var doc struct {
		Source string       `json:"source"`
		States []skillState `json:"states"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}
	if len(doc.States) == 0 {
		t.Fatalf("%s carries no states", path)
	}

	table := make(map[counts]skillState, len(doc.States))
	for _, s := range doc.States {
		table[counts{s.LiveSystems, s.BuildingSystems}] = s
	}
	return table
}

// ----------------------------------------------------------------- the stage

type poolSystem struct {
	id    int64
	state string
}

// systemPool seeds three systems in each of the three states. Three, not two:
// with only two live systems the grid could not tell `>= 2` from `= 2`, and that
// is exactly the boundary the derivation turns on.
func systemPool(t *testing.T, db *sql.DB) []poolSystem {
	t.Helper()

	states := []string{"live", "live", "live", "in_build", "in_build", "in_build", "queued", "queued", "queued"}
	pool := make([]poolSystem, 0, len(states))

	for i, state := range states {
		var id int64
		err := db.QueryRow(`
			INSERT INTO systems (slug, system_no, name, state, source_access, source_url)
			VALUES ($1, $2, $3, $4, 'public', 'https://github.com/G1NG4R/example')
			RETURNING id`,
			"sys-"+twoDigits(i+1), twoDigits(i+1), "System "+twoDigits(i+1), state,
		).Scan(&id)
		if err != nil {
			t.Fatalf("seeding system %d: %v", i+1, err)
		}
		pool = append(pool, poolSystem{id: id, state: state})
	}
	return pool
}

func twoDigits(n int) string { return fmt.Sprintf("%02d", n) }

func insertModule(t failer, q querier, no, title string) int64 {
	var id int64
	if err := q.QueryRow(
		`INSERT INTO modules (module_no, title) VALUES ($1, $2) RETURNING id`, no, title,
	).Scan(&id); err != nil {
		t.Fatalf("seeding module %s: %v", no, err)
	}
	return id
}

func insertTrack(t failer, q querier, moduleID int64, name string, order int) int64 {
	var id int64
	if err := q.QueryRow(
		`INSERT INTO tracks (module_id, name, sort_order) VALUES ($1, $2, $3) RETURNING id`,
		moduleID, name, order,
	).Scan(&id); err != nil {
		t.Fatalf("seeding track %q: %v", name, err)
	}
	return id
}

// readState fetches the one row the view must have for this track. sql.ErrNoRows
// is reported as the failure it is: a track missing from the derivation is worse
// than a track in the wrong state, because nothing downstream would notice.
func readState(t failer, q querier, trackID int64) (int, int, string) {
	var live, building int
	var state string
	err := q.QueryRow(`
		SELECT live_systems, building_systems, state
		  FROM v_track_states WHERE track_id = $1`, trackID).Scan(&live, &building, &state)
	if err == sql.ErrNoRows {
		t.Fatalf("track %d has no row in v_track_states — an inner join would do that, and it would hide every track without evidence", trackID)
	}
	if err != nil {
		t.Fatalf("reading v_track_states: %v", err)
	}
	return live, building, state
}

// ------------------------------------------------------------- the property

// TestTrackStateMatchesTheDesignReference is the phase's acceptance criterion,
// word for word: a thousand generated evidence constellations, and both sides
// agree.
//
// Each case builds one track, hangs a random distinct subset of the system pool
// off it, and rolls the whole thing back — so the thousand cases share one
// schema and one pool, and the constellation is the only thing that varies.
func TestTrackStateMatchesTheDesignReference(t *testing.T) {
	db := freshSchema(t)
	reference := loadSkillStates(t)
	pool := systemPool(t, db)
	moduleID := insertModule(t, db, "01", "Property")

	seen := map[string]int{}

	rapid.Check(t, func(rt *rapid.T) {
		evidence := rapid.SliceOfNDistinct(
			rapid.SampledFrom(pool), 0, len(pool),
			func(s poolSystem) int64 { return s.id },
		).Draw(rt, "evidence")

		tx, err := db.Begin()
		if err != nil {
			rt.Fatalf("beginning a transaction: %v", err)
		}
		defer func() { _ = tx.Rollback() }()

		trackID := insertTrack(rt, tx, moduleID, "property", 1)

		var want counts
		for _, s := range evidence {
			if _, err := tx.Exec(
				`INSERT INTO track_evidence (track_id, system_id) VALUES ($1, $2)`,
				trackID, s.id,
			); err != nil {
				rt.Fatalf("inserting evidence on system %d: %v", s.id, err)
			}
			switch s.state {
			case "live":
				want.live++
			case "in_build":
				want.building++
			}
		}

		live, building, state := readState(rt, tx, trackID)

		// The counters first. A FILTER that counts the wrong rows can still land
		// on the right state by accident; asking separately takes the accident
		// out of it.
		if live != want.live || building != want.building {
			rt.Fatalf("counted %d live and %d building, want %d and %d",
				live, building, want.live, want.building)
		}

		ref, ok := reference[want]
		if !ok {
			rt.Fatalf("no reference for %d live / %d building — regenerate testdata/skill_states.json (make gen)",
				want.live, want.building)
		}
		if state != ref.API {
			rt.Fatalf("%d live / %d building: the view says %q, %s says %q",
				want.live, want.building, state, "skillState()", ref.API)
		}

		// The case rule from phase C3, pinned to a file instead of to a memory:
		// the API speaks lowercase, the design sheets speak uppercase, and the
		// two differ in nothing else.
		if strings.ToUpper(state) != ref.UI {
			rt.Fatalf("the view says %q, the design reference renders %q", state, ref.UI)
		}

		// And the contract, which is the third party to this agreement.
		if !httpx.TrackState(state).Valid() {
			rt.Fatalf("the view produced %q, which the contract's TrackState does not know", state)
		}

		seen[state]++
	})

	// A thousand green cases prove nothing if they all sat in one corner of the
	// grid. Every state the contract knows has to have actually occurred.
	for _, want := range []httpx.TrackState{
		httpx.TrackStateCore, httpx.TrackStateApplied,
		httpx.TrackStateLearning, httpx.TrackStateQueued,
	} {
		if seen[string(want)] == 0 {
			t.Errorf("no generated constellation ever produced %q — the generator is not covering the grid", want)
		}
	}
	t.Logf("coverage: core=%d applied=%d learning=%d queued=%d",
		seen["core"], seen["applied"], seen["learning"], seen["queued"])
}

// ---------------------------------------------------------- the broken cases

// The failure that would be invisible: with an inner join a track without
// evidence does not turn `queued`, it disappears. Nine of the twenty-two tracks
// are self-study at launch, and the training log would silently drop them —
// looking fuller by hiding the honest rows.
func TestTrackWithoutEvidenceIsQueuedAndPresent(t *testing.T) {
	db := freshSchema(t)
	moduleID := insertModule(t, db, "02", "Self-study")
	trackID := insertTrack(t, db, moduleID, "Kubernetes", 1)

	live, building, state := readState(t, db, trackID)
	if live != 0 || building != 0 {
		t.Errorf("a track with no evidence counts %d live and %d building, want zero and zero", live, building)
	}
	if state != string(httpx.TrackStateQueued) {
		t.Errorf("a track with no evidence is %q, want %q", state, httpx.TrackStateQueued)
	}

	var rows int
	if err := db.QueryRow(`SELECT count(*) FROM v_track_states`).Scan(&rows); err != nil {
		t.Fatalf("counting the derivation: %v", err)
	}
	if rows != 1 {
		t.Errorf("the derivation has %d rows for one track — it must have exactly one", rows)
	}
}

// A row in track_evidence is not proof. It points at a system, and a system that
// does not run proves nothing about a skill — that is the whole argument of the
// site, and here it is a query.
func TestQueuedSystemsProveNothing(t *testing.T) {
	db := freshSchema(t)
	moduleID := insertModule(t, db, "03", "Planned")
	trackID := insertTrack(t, db, moduleID, "Terraform", 1)

	for i, slug := range []string{"planned-a", "planned-b"} {
		var id int64
		if err := db.QueryRow(`
			INSERT INTO systems (slug, system_no, name, state, source_access, source_reason)
			VALUES ($1, $2, $3, 'queued', 'private', 'internal') RETURNING id`,
			slug, twoDigits(i+1), slug,
		).Scan(&id); err != nil {
			t.Fatalf("seeding %s: %v", slug, err)
		}
		if _, err := db.Exec(
			`INSERT INTO track_evidence (track_id, system_id) VALUES ($1, $2)`, trackID, id,
		); err != nil {
			t.Fatalf("attaching %s: %v", slug, err)
		}
	}

	live, building, state := readState(t, db, trackID)
	if live != 0 || building != 0 {
		t.Errorf("queued systems counted as %d live and %d building, want zero and zero", live, building)
	}
	if state != string(httpx.TrackStateQueued) {
		t.Errorf("two queued systems made the track %q, want %q", state, httpx.TrackStateQueued)
	}
}

// ADR 0003, first consequence, and the criterion phase C3 will be measured on:
// setting a system live moves its tracks without anybody maintaining a row. The
// xmin comparison is the second half of that sentence — it proves the track row
// itself was never written.
func TestFlippingASystemToLiveMovesItsTracks(t *testing.T) {
	db := freshSchema(t)
	moduleID := insertModule(t, db, "04", "DevOps")
	trackID := insertTrack(t, db, moduleID, "CI/CD (GitHub Actions)", 1)

	var systemID int64
	if err := db.QueryRow(`
		INSERT INTO systems (slug, system_no, name, state, source_access, source_url)
		VALUES ('vat-check', '01', 'vat-check', 'in_build', 'public',
		        'https://github.com/G1NG4R/vat-check')
		RETURNING id`).Scan(&systemID); err != nil {
		t.Fatalf("seeding the system: %v", err)
	}
	if _, err := db.Exec(
		`INSERT INTO track_evidence (track_id, system_id) VALUES ($1, $2)`, trackID, systemID,
	); err != nil {
		t.Fatalf("attaching the evidence: %v", err)
	}

	if _, _, state := readState(t, db, trackID); state != string(httpx.TrackStateLearning) {
		t.Fatalf("a system in build makes the track %q, want %q", state, httpx.TrackStateLearning)
	}

	var before, after string
	if err := db.QueryRow(`SELECT xmin::text FROM tracks WHERE id = $1`, trackID).Scan(&before); err != nil {
		t.Fatalf("reading the row version: %v", err)
	}

	if _, err := db.Exec(`UPDATE systems SET state = 'live' WHERE id = $1`, systemID); err != nil {
		t.Fatalf("setting the system live: %v", err)
	}

	live, building, state := readState(t, db, trackID)
	if state != string(httpx.TrackStateApplied) {
		t.Errorf("after the system went live the track is %q, want %q", state, httpx.TrackStateApplied)
	}
	if live != 1 || building != 0 {
		t.Errorf("counted %d live and %d building after the flip, want one and zero", live, building)
	}

	if err := db.QueryRow(`SELECT xmin::text FROM tracks WHERE id = $1`, trackID).Scan(&after); err != nil {
		t.Fatalf("reading the row version again: %v", err)
	}
	if before != after {
		t.Errorf("the track row was written (xmin %s -> %s) — the state is supposed to be derived, not maintained", before, after)
	}
}

// The view is created with security_invoker, so reading it uses the caller's
// rights rather than the owner's. That is the right setting and it has a price:
// the app role needs SELECT on all three base tables. A permission error belongs
// here, next to its cause, and not in a C3 handler.
func TestAppRoleCanReadTheDerivation(t *testing.T) {
	migrate := freshSchema(t)
	moduleID := insertModule(t, migrate, "05", "Foundations")
	trackID := insertTrack(t, migrate, moduleID, "PostgreSQL", 1)

	app := appDB(t)

	live, building, state := readState(t, app, trackID)
	if live != 0 || building != 0 || state != string(httpx.TrackStateQueued) {
		t.Errorf("the app role reads %d/%d/%q, want 0/0/%q", live, building, state, httpx.TrackStateQueued)
	}

	// The derivation is an aggregate, so it is not auto-updatable. The app role
	// carries INSERT on it from ALTER DEFAULT PRIVILEGES, and Postgres still
	// refuses — which is the point: there is no way to write a state.
	mustReject(t, app, "writing a state into the derivation", `
		INSERT INTO v_track_states (track_id, live_systems, building_systems, state)
		VALUES (1, 2, 0, 'core')`)
}
