/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness, build identity and operational metrics
         * @description The deploy gate polls this endpoint: no `200` within sixty seconds of a
         *     release and the pipeline rolls back. The README badges read it too.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every tracked system with its state, its source and its metrics
         * @description The proving ground of this site. Every system with `state` other than `live`
         *     carries `null` in **every** metric field — there is nothing to measure.
         */
        get: operations["listSystems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One system with its operation grid, incidents and deploys
         * @description `days`, `incidents` and `deploys` are present only for `state: live`.
         *
         *     A day without a measurement is `nodata`, never `ok` — on day one the whole
         *     grid is `nodata`. Uptime, MTTR and rollback rate are computed from `days` and
         *     `deploys` by the caller; they are never delivered as separate numbers, so
         *     they cannot disagree with the grid a reader can count.
         */
        get: operations["getSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Modules, tracks and the systems that prove them
         * @description Track states are **derived** from evidence, not stored: two live systems make
         *     a track `core`, one makes it `applied`, a system still in build makes it
         *     `learning`, nothing makes it `queued`. There is no state column to drift.
         *
         *     An empty `evidence` array is the honest case and renders as
         *     `NO SYSTEM YET → SELF-STUDY`.
         */
        get: operations["getTraining"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The GitHub contribution calendar, fetched server-side
         * @description Cached for an hour behind a circuit breaker. If GitHub does not answer, the
         *     last good calendar is returned with its age in `cacheAgeSec` rather than an
         *     error — an old number with a date is honest, an empty one is not.
         *
         *     `level` uses this site's own five steps. GitHub's colours are not passed
         *     through.
         */
        get: operations["getContributions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message
         * @description Rate limited to three requests per IP per ten minutes; the IP is stored as a
         *     hash only. `company` is a honeypot and must be empty. `dwellMs` below 3000
         *     is discarded. Repeating the same `ts` + `email` + message delivers once.
         */
        post: operations["submitContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This contract, rendered
         * @description Served from the API binary with no third-party request in the reader's path.
         *     Internal operations are stripped from the document this page reads.
         */
        get: operations["getDocs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/scalar.js": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The renderer that /api/docs loads
         * @description Vendored into the binary rather than pulled from a CDN. It is listed here
         *     because it is a route that exists, and a route that exists but is documented
         *     nowhere is exactly what the router parity check looks for.
         */
        get: operations["getDocsAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This contract, raw
         * @description The public bundle — the same document `/api/docs` renders.
         */
        get: operations["getOpenapiDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/badge/uptime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Shields.io endpoint badge — uptime
         * @description Live because it asks the API on every call: no scheduled job, no commit, no
         *     collision with branch protection. Without a measurement series the badge
         *     reads `— NO DATA`, not a zero.
         */
        get: operations["getUptimeBadge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/badge/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shields.io endpoint badge — deployed version */
        get: operations["getVersionBadge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/badge/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shields.io endpoint badge — live systems */
        get: operations["getSystemsBadge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * An external prober reports that the host answered
         * @description A host cannot report its own outage. This is written by a watcher that runs
         *     somewhere else; when it cannot reach the host at all it writes to the
         *     `ops-data` branch instead.
         *
         *     The path may move out of `/api/internal/*` in L3 — the reverse proxy blocks
         *     that prefix from outside, and the prober calls from outside. `operationId`
         *     stays put so a path change is not a contract break.
         */
        post: operations["reportProbe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The pipeline reports its own duration
         * @description This is why the deploy duration on the case study is measured rather than
         *     claimed.
         */
        post: operations["reportDeploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Problem
         * @description RFC 9457 Problem Details, used for **every** error response including
         *     `/api/contact`. Two error shapes in one API is the kind of special case
         *     somebody misses later.
         *
         *     `detail` never carries a stack trace or a database message — those go to the
         *     log, keyed by `requestId`.
         */
        Problem: {
            /**
             * Format: uri
             * @description A URI under `https://timseil.dev/problems/`.
             * @example https://timseil.dev/problems/validation-failed
             */
            type: string;
            /**
             * @description Short, human-readable, stable for a given `type`.
             * @example Validation failed
             */
            title: string;
            /** @example 400 */
            status: number;
            /** @description What went wrong with *this* request. Safe to show a visitor. */
            detail?: string;
            /**
             * @description The path that produced it.
             * @example /api/contact
             */
            instance?: string;
            /**
             * @description Also sent as the `X-Request-Id` response header. Quoting it in a bug
             *     report finds every log line from both services.
             */
            requestId?: string;
            /** @description Present on `400` only, one entry per rejected field. */
            invalidParams?: components["schemas"]["InvalidParam"][];
        };
        InvalidParam: {
            /** @example email */
            name: string;
            /** @example not a valid address */
            reason: string;
        };
        /**
         * @description What the system *does*. Independent of who may read its code.
         * @enum {string}
         */
        SystemState: "live" | "in_build" | "queued";
        /**
         * @description Derived from evidence, never stored. `core` needs two live systems: building
         *     something once means getting it to run once; running it twice means having met
         *     the cases that were luck the first time.
         * @enum {string}
         */
        TrackState: "core" | "applied" | "learning" | "queued";
        /**
         * @description `nodata` is the important one. A day without a measurement is `nodata`, never
         *     `ok` — an empty grid is more honest than a full one that was invented.
         * @enum {string}
         */
        DayState: "ok" | "degraded" | "outage" | "nodata";
        /** @enum {string} */
        DeployResult: "ok" | "rollback";
        /**
         * @description Why a closed system is closed. `<> PRIVATE · NDA` is an honest statement;
         *     `<> PRIVATE` with no reason would be an excuse, so the contract requires one.
         * @enum {string}
         */
        SourceReason: "nda" | "internal";
        /**
         * @description This site's own five steps, mapped from GitHub's quartiles.
         * @enum {string}
         */
        ContributionLevel: "l0" | "l1" | "l2" | "l3" | "l4";
        /**
         * Metrics
         * @description Every field is nullable and that is the point. `null` renders as `— NO DATA`;
         *     `0` is a real measurement and must never stand in for a missing one.
         *
         *     Only systems in state `live` carry values here.
         */
        Metrics: {
            /**
             * Format: double
             * @description Share of time the system answered, as a percentage. The name says 90 for
             *     historical reasons; the window is **91 days** (13 × 7) everywhere else in
             *     this contract and on the site.
             * @example 99.64
             */
            uptime90d: number | null;
            /**
             * Format: double
             * @description 95th percentile latency, measured at the reverse proxy.
             * @example 142
             */
            p95Ms: number | null;
            /**
             * Format: double
             * @description Share of 5xx responses, as a fraction between 0 and 1.
             * @example 0.0007
             */
            errorRate: number | null;
            /**
             * Format: date-time
             * @description When these values were taken. A value without its age cannot be told apart
             *     from a fresh one, and the site shows stale numbers *with* their age rather
             *     than pretending.
             */
            measuredAt: string | null;
        };
        /** Health */
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /**
             * @description Release tag of the running binary.
             * @example 1.4.0
             */
            version: string;
            /**
             * @description Commit the binary was built from.
             * @example a41f9c2
             */
            sha: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            generatedAt: string;
            ops: components["schemas"]["OpsSummary"];
        };
        OpsSummary: components["schemas"]["Metrics"] & {
            systemsLive: number;
            systemsTotal: number;
            lastDeploy: components["schemas"]["Deploy"] | null;
        };
        /**
         * Badge
         * @description The payload Shields.io expects from an endpoint badge. It is a foreign schema,
         *     but it belongs in this contract — three routes that exist and are documented
         *     nowhere would fail the router parity check.
         */
        Badge: {
            /** @constant */
            schemaVersion: 1;
            /** @example uptime */
            label: string;
            /**
             * @description `— NO DATA` when there is no measurement series.
             * @example 99.64%
             */
            message: string;
            /** @example brightgreen */
            color?: string;
            isError?: boolean;
            /** @example 300 */
            cacheSeconds?: number;
        };
        SourcePublic: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            access: "public";
            /**
             * Format: uri
             * @example https://github.com/G1NG4R/timseil-dev
             */
            url: string;
        };
        SourcePrivate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            access: "private";
            reason: components["schemas"]["SourceReason"];
        };
        /**
         * Source
         * @description How the code can be reached. This is a separate axis from `state`: a system can
         *     be open and not running, or running and closed. Squeezing both into one field
         *     is the classic modelling mistake — you notice it when the first NDA client
         *     arrives.
         */
        Source: components["schemas"]["SourcePublic"] | components["schemas"]["SourcePrivate"];
        /** System */
        System: {
            /** @example timseil-dev */
            slug: string;
            /**
             * @description Two-digit display number, zero padded.
             * @example 02
             */
            systemNo: string;
            /** @example timseil.dev */
            name: string;
            state: components["schemas"]["SystemState"];
            source: components["schemas"]["Source"];
            /**
             * @description Curated in `stack.yaml`, versions checked against `go.mod`,
             *     `package.json` and `compose.yaml` in CI. Nobody types a version number
             *     into a page again.
             * @example [
             *       "Next.js 16.3",
             *       "Go 1.26",
             *       "PostgreSQL 18.6"
             *     ]
             */
            stack: string[];
            metrics: components["schemas"]["Metrics"];
        };
        SystemList: {
            systems: components["schemas"]["System"][];
            /** Format: date-time */
            generatedAt: string;
        };
        OpsDay: {
            /**
             * Format: date
             * @example 2026-06-12
             */
            d: string;
            state: components["schemas"]["DayState"];
            /** @example 2520 */
            downSec: number;
            /**
             * @description Set when the day carries a notch.
             * @example INC-001
             */
            incidentId?: string;
        };
        /**
         * @description `cause`, `fix` and `postSlug` are required, and that is a schema rule rather
         *     than a resolution: a red cell without an explanation is worse than none. With
         *     one, the same outage becomes evidence of operational maturity.
         */
        Incident: {
            /** @example INC-001 */
            id: string;
            /** Format: date-time */
            startedAt: string;
            durationSec: number;
            cause: string;
            fix: string;
            /**
             * @description The post-mortem entry in the log.
             * @example 011-migration-lock
             */
            postSlug: string;
        };
        Deploy: {
            /** @example a41f9c2 */
            sha: string;
            /**
             * @description Reported by the pipeline itself, not estimated.
             * @example 42
             */
            durationSec: number;
            result: components["schemas"]["DeployResult"];
            /** Format: date-time */
            at: string;
        };
        SystemDetail: components["schemas"]["System"] & {
            /**
             * @description How many days `days` covers.
             * @example 91
             */
            window: number;
            /** Format: date-time */
            generatedAt: string;
            /** @description Absent unless `state` is `live`. */
            days?: components["schemas"]["OpsDay"][];
            /** @description Absent unless `state` is `live`. */
            incidents?: components["schemas"]["Incident"][];
            /** @description Absent unless `state` is `live`. */
            deploys?: components["schemas"]["Deploy"][];
        };
        /** @description One system in which a track actually runs. */
        Evidence: {
            /** @example timseil-dev */
            systemId: string;
            /** @example 02 */
            systemNo: string;
            /** @example build + deploy */
            detail?: string;
        };
        Track: {
            /** @example CI/CD (GitHub Actions) */
            name: string;
            state: components["schemas"]["TrackState"];
            /** @description Empty means no system yet — self-study, and said so plainly. */
            evidence: components["schemas"]["Evidence"][];
            /**
             * @description Set only when `evidence` is empty.
             * @example self-study
             */
            note?: string;
        };
        Module: {
            /** @example 04 */
            no: string;
            /** @example DevOps */
            title: string;
            tracks: components["schemas"]["Track"][];
        };
        Training: {
            modules: components["schemas"]["Module"][];
            /** @example 22 */
            trackCount: number;
            /**
             * @description Distinct systems backing at least one track.
             * @example 1
             */
            evidenceSystems: number;
            /** Format: date-time */
            generatedAt: string;
        };
        ContributionDay: {
            /** Format: date */
            date: string;
            count: number;
            level: components["schemas"]["ContributionLevel"];
        };
        ContributionWeek: {
            days: components["schemas"]["ContributionDay"][];
        };
        Contributions: {
            totalContributions: number;
            /** Format: date-time */
            fetchedAt: string;
            /**
             * @description How old this calendar is. When GitHub is unreachable the site shows the
             *     last good one *with* this age rather than an error.
             */
            cacheAgeSec: number;
            weeks: components["schemas"]["ContributionWeek"][];
        };
        /**
         * ContactRequest
         * @description The contact page renders this exact payload live as the visitor types, so a
         *     field name here is also a design decision.
         */
        ContactRequest: {
            name: string;
            /**
             * Format: email
             * @description Becomes the `Reply-To` header. A `\r` or `\n` in here would let an attacker
             *     append their own headers and turn the form into a spam relay on this
             *     domain — rejected outright.
             */
            email: string;
            message: string;
            /** @description Honeypot. Must be empty; anything else is discarded silently. */
            company: string;
            /** @description Time on the form. Under three seconds is not a human. */
            dwellMs: number;
            /**
             * Format: date-time
             * @description With `email` and a hash of `message`, this makes a resend idempotent.
             */
            ts: string;
        };
        ContactAccepted: {
            /** @constant */
            ok: true;
            /**
             * @description The receipt. The sender's text stays in the field.
             * @example msg_01K3F9QX7A
             */
            id: string;
        };
        ProbeReport: {
            /** Format: date-time */
            at: string;
            up: boolean;
            latencyMs?: number;
            /**
             * @description Set when `up` is false.
             * @example connect timeout
             */
            reason?: string;
        };
        DeployReport: {
            sha: string;
            durationSec: number;
            result: components["schemas"]["DeployResult"];
            /** Format: date-time */
            at: string;
        };
    };
    responses: {
        /** @description The representation has not changed since the given `ETag`. */
        NotModified: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Recorded. */
        AcceptedNoContent: {
            headers: {
                "Cache-Control": components["headers"]["CacheControlNone"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description A Shields.io endpoint payload. */
        BadgeOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControlMedium"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Badge"];
            };
        };
        /** @description The request did not validate. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or wrong token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description An upstream this endpoint depends on did not answer. */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Something broke on our side. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description The system's stable identifier, for example `timseil-dev`.
         * @example timseil-dev
         */
        Slug: string;
        /**
         * @description How many days of the operation grid to return. 91 is 13 × 7 — seven rows only
         *     hold multiples of seven, and at 90 the last column would have a hole that
         *     looks like a bug. 30 is the homepage strip, 182 is the wide view.
         */
        Window: 30 | 91 | 182;
        /** @description The `ETag` of a previously fetched representation. */
        IfNoneMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Entity tag of this representation. */
        ETag: string;
        /** @description Cache directive. */
        CacheControlShort: "public, s-maxage=60, stale-while-revalidate=600";
        /** @description Cache directive. */
        CacheControlMedium: "public, s-maxage=300, stale-while-revalidate=1800";
        /** @description Cache directive. */
        CacheControlHour: "public, s-maxage=3600, stale-while-revalidate=7200";
        /** @description Cache directive. */
        CacheControlNone: "no-store";
        /**
         * @description Seconds to wait before retrying. Always a count of seconds, never an
         *     HTTP-date — RFC 9110 permits both, and a client that has to guess which
         *     one arrived will guess wrong once.
         */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` of a previously fetched representation. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControlShort"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            304: components["responses"]["NotModified"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listSystems: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` of a previously fetched representation. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list of systems. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControlMedium"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemList"];
                };
            };
            304: components["responses"]["NotModified"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getSystem: {
        parameters: {
            query?: {
                /**
                 * @description How many days of the operation grid to return. 91 is 13 × 7 — seven rows only
                 *     hold multiples of seven, and at 90 the last column would have a hole that
                 *     looks like a bug. 30 is the homepage strip, 182 is the wide view.
                 */
                window?: components["parameters"]["Window"];
            };
            header?: {
                /** @description The `ETag` of a previously fetched representation. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                /**
                 * @description The system's stable identifier, for example `timseil-dev`.
                 * @example timseil-dev
                 */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The system. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControlMedium"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemDetail"];
                };
            };
            304: components["responses"]["NotModified"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getTraining: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` of a previously fetched representation. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The training log. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControlMedium"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Training"];
                };
            };
            304: components["responses"]["NotModified"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getContributions: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` of a previously fetched representation. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contribution calendar. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControlHour"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contributions"];
                };
            };
            304: components["responses"]["NotModified"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
        };
    };
    submitContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /**
             * @description Accepted for delivery. The message id is the receipt the sender can
             *     quote — the form keeps their text in the field.
             */
            202: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControlNone"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
        };
    };
    getDocs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rendered reference. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControlHour"];
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getDocsAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The renderer bundle. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControlHour"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "text/javascript": string;
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getOpenapiDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI document. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControlHour"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getUptimeBadge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BadgeOK"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getVersionBadge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BadgeOK"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getSystemsBadge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BadgeOK"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    reportProbe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeReport"];
            };
        };
        responses: {
            204: components["responses"]["AcceptedNoContent"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    reportDeploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployReport"];
            };
        };
        responses: {
            204: components["responses"]["AcceptedNoContent"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
}
