//go:build go1.22

// Package httpx provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpx

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BadgeSchemaVersion.
const (
	N1 BadgeSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the BadgeSchemaVersion enum.
func (e BadgeSchemaVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for ContactAcceptedOk.
const (
	True ContactAcceptedOk = true
)

// Valid indicates whether the value is a known member of the ContactAcceptedOk enum.
func (e ContactAcceptedOk) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for ContributionLevel.
const (
	L0 ContributionLevel = "l0"
	L1 ContributionLevel = "l1"
	L2 ContributionLevel = "l2"
	L3 ContributionLevel = "l3"
	L4 ContributionLevel = "l4"
)

// Valid indicates whether the value is a known member of the ContributionLevel enum.
func (e ContributionLevel) Valid() bool {
	switch e {
	case L0:
		return true
	case L1:
		return true
	case L2:
		return true
	case L3:
		return true
	case L4:
		return true
	default:
		return false
	}
}

// Defines values for DayState.
const (
	DayStateDegraded DayState = "degraded"
	DayStateNodata   DayState = "nodata"
	DayStateOk       DayState = "ok"
	DayStateOutage   DayState = "outage"
)

// Valid indicates whether the value is a known member of the DayState enum.
func (e DayState) Valid() bool {
	switch e {
	case DayStateDegraded:
		return true
	case DayStateNodata:
		return true
	case DayStateOk:
		return true
	case DayStateOutage:
		return true
	default:
		return false
	}
}

// Defines values for DeployResult.
const (
	DeployResultOk       DeployResult = "ok"
	DeployResultRollback DeployResult = "rollback"
)

// Valid indicates whether the value is a known member of the DeployResult enum.
func (e DeployResult) Valid() bool {
	switch e {
	case DeployResultOk:
		return true
	case DeployResultRollback:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for SourcePrivateAccess.
const (
	Private SourcePrivateAccess = "private"
)

// Valid indicates whether the value is a known member of the SourcePrivateAccess enum.
func (e SourcePrivateAccess) Valid() bool {
	switch e {
	case Private:
		return true
	default:
		return false
	}
}

// Defines values for SourcePublicAccess.
const (
	Public SourcePublicAccess = "public"
)

// Valid indicates whether the value is a known member of the SourcePublicAccess enum.
func (e SourcePublicAccess) Valid() bool {
	switch e {
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for SourceReason.
const (
	Internal SourceReason = "internal"
	Nda      SourceReason = "nda"
)

// Valid indicates whether the value is a known member of the SourceReason enum.
func (e SourceReason) Valid() bool {
	switch e {
	case Internal:
		return true
	case Nda:
		return true
	default:
		return false
	}
}

// Defines values for SystemState.
const (
	SystemStateInBuild SystemState = "in_build"
	SystemStateLive    SystemState = "live"
	SystemStateQueued  SystemState = "queued"
)

// Valid indicates whether the value is a known member of the SystemState enum.
func (e SystemState) Valid() bool {
	switch e {
	case SystemStateInBuild:
		return true
	case SystemStateLive:
		return true
	case SystemStateQueued:
		return true
	default:
		return false
	}
}

// Defines values for TrackState.
const (
	TrackStateApplied  TrackState = "applied"
	TrackStateCore     TrackState = "core"
	TrackStateLearning TrackState = "learning"
	TrackStateQueued   TrackState = "queued"
)

// Valid indicates whether the value is a known member of the TrackState enum.
func (e TrackState) Valid() bool {
	switch e {
	case TrackStateApplied:
		return true
	case TrackStateCore:
		return true
	case TrackStateLearning:
		return true
	case TrackStateQueued:
		return true
	default:
		return false
	}
}

// Defines values for Window.
const (
	WindowN182 Window = 182
	WindowN30  Window = 30
	WindowN91  Window = 91
)

// Valid indicates whether the value is a known member of the Window enum.
func (e Window) Valid() bool {
	switch e {
	case WindowN182:
		return true
	case WindowN30:
		return true
	case WindowN91:
		return true
	default:
		return false
	}
}

// Defines values for GetSystemParamsWindow.
const (
	GetSystemParamsWindowN182 GetSystemParamsWindow = 182
	GetSystemParamsWindowN30  GetSystemParamsWindow = 30
	GetSystemParamsWindowN91  GetSystemParamsWindow = 91
)

// Valid indicates whether the value is a known member of the GetSystemParamsWindow enum.
func (e GetSystemParamsWindow) Valid() bool {
	switch e {
	case GetSystemParamsWindowN182:
		return true
	case GetSystemParamsWindowN30:
		return true
	case GetSystemParamsWindowN91:
		return true
	default:
		return false
	}
}

// Badge The payload Shields.io expects from an endpoint badge. It is a foreign schema,
// but it belongs in this contract — three routes that exist and are documented
// nowhere would fail the router parity check.
type Badge struct {
	// CacheSeconds Examples: 300
	CacheSeconds *int `json:"cacheSeconds,omitempty"`

	// Color Examples: brightgreen
	Color   *string `json:"color,omitempty"`
	IsError *bool   `json:"isError,omitempty"`

	// Label Examples: uptime
	Label string `json:"label"`

	// Message `— NO DATA` when there is no measurement series.
	//
	// Examples: 99.64%
	Message       string             `json:"message"`
	SchemaVersion BadgeSchemaVersion `json:"schemaVersion"`
}

// BadgeSchemaVersion defines model for Badge.SchemaVersion.
type BadgeSchemaVersion int

// ContactAccepted defines model for ContactAccepted.
type ContactAccepted struct {
	// Id The receipt. The sender's text stays in the field.
	//
	// Examples: msg_01K3F9QX7A
	Id string            `json:"id"`
	Ok ContactAcceptedOk `json:"ok"`
}

// ContactAcceptedOk defines model for ContactAccepted.Ok.
type ContactAcceptedOk bool

// ContactRequest The contact page renders this exact payload live as the visitor types, so a
// field name here is also a design decision.
type ContactRequest struct {
	// Company Honeypot. Must be empty; anything else is discarded silently.
	Company string `json:"company"`

	// DwellMs Time on the form. Under three seconds is not a human.
	DwellMs int `json:"dwellMs"`

	// Email Becomes the `Reply-To` header. A `\r` or `\n` in here would let an attacker
	// append their own headers and turn the form into a spam relay on this
	// domain — rejected outright.
	Email   openapi_types.Email `json:"email"`
	Message string              `json:"message"`
	Name    string              `json:"name"`

	// Ts With `email` and a hash of `message`, this makes a resend idempotent.
	Ts time.Time `json:"ts"`
}

// ContributionDay defines model for ContributionDay.
type ContributionDay struct {
	Count int                `json:"count"`
	Date  openapi_types.Date `json:"date"`

	// Level This site's own five steps, mapped from GitHub's quartiles.
	Level ContributionLevel `json:"level"`
}

// ContributionLevel This site's own five steps, mapped from GitHub's quartiles.
type ContributionLevel string

// ContributionWeek defines model for ContributionWeek.
type ContributionWeek struct {
	Days []ContributionDay `json:"days"`
}

// Contributions defines model for Contributions.
type Contributions struct {
	// CacheAgeSec How old this calendar is. When GitHub is unreachable the site shows the
	// last good one *with* this age rather than an error.
	CacheAgeSec        int                `json:"cacheAgeSec"`
	FetchedAt          time.Time          `json:"fetchedAt"`
	TotalContributions int                `json:"totalContributions"`
	Weeks              []ContributionWeek `json:"weeks"`
}

// DayState `nodata` is the important one. A day without a measurement is `nodata`, never
// `ok` — an empty grid is more honest than a full one that was invented.
type DayState string

// Deploy defines model for Deploy.
type Deploy struct {
	At time.Time `json:"at"`

	// DurationSec Reported by the pipeline itself, not estimated.
	//
	// Examples: 42
	DurationSec int          `json:"durationSec"`
	Result      DeployResult `json:"result"`

	// Sha Examples: a41f9c2
	Sha string `json:"sha"`
}

// DeployReport defines model for DeployReport.
type DeployReport struct {
	At          time.Time    `json:"at"`
	DurationSec int          `json:"durationSec"`
	Result      DeployResult `json:"result"`
	Sha         string       `json:"sha"`
}

// DeployResult defines model for DeployResult.
type DeployResult string

// Evidence One system in which a track actually runs.
type Evidence struct {
	// Detail Examples: build + deploy
	Detail *string `json:"detail,omitempty"`

	// SystemId Examples: timseil-dev
	SystemId string `json:"systemId"`

	// SystemNo Examples: 02
	SystemNo string `json:"systemNo"`
}

// Health defines model for Health.
type Health struct {
	GeneratedAt time.Time  `json:"generatedAt"`
	Ops         OpsSummary `json:"ops"`

	// Sha Commit the binary was built from.
	//
	// Examples: a41f9c2
	Sha       string       `json:"sha"`
	StartedAt time.Time    `json:"startedAt"`
	Status    HealthStatus `json:"status"`

	// Version Release tag of the running binary.
	//
	// Examples: 1.4.0
	Version string `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Incident `cause`, `fix` and `postSlug` are required, and that is a schema rule rather
// than a resolution: a red cell without an explanation is worse than none. With
// one, the same outage becomes evidence of operational maturity.
type Incident struct {
	Cause       string `json:"cause"`
	DurationSec int    `json:"durationSec"`
	Fix         string `json:"fix"`

	// Id Examples: INC-001
	Id string `json:"id"`

	// PostSlug The post-mortem entry in the log.
	//
	// Examples: 011-migration-lock
	PostSlug  string    `json:"postSlug"`
	StartedAt time.Time `json:"startedAt"`
}

// InvalidParam defines model for InvalidParam.
type InvalidParam struct {
	// Name Examples: email
	Name string `json:"name"`

	// Reason Examples: not a valid address
	Reason string `json:"reason"`
}

// Metrics Every field is nullable and that is the point. `null` renders as `— NO DATA`;
// `0` is a real measurement and must never stand in for a missing one.
//
// Only systems in state `live` carry values here.
type Metrics struct {
	// ErrorRate Share of 5xx responses, as a fraction between 0 and 1.
	//
	// Examples: 0.0007
	ErrorRate *float64 `json:"errorRate"`

	// MeasuredAt When these values were taken. A value without its age cannot be told apart
	// from a fresh one, and the site shows stale numbers *with* their age rather
	// than pretending.
	MeasuredAt *time.Time `json:"measuredAt"`

	// P95Ms 95th percentile latency, measured at the reverse proxy.
	//
	// Examples: 142
	P95Ms *float64 `json:"p95Ms"`

	// Uptime90d Share of time the system answered, as a percentage. The name says 90 for
	// historical reasons; the window is **91 days** (13 × 7) everywhere else in
	// this contract and on the site.
	//
	//
	// Examples: 99.64
	Uptime90d *float64 `json:"uptime90d"`
}

// Module defines model for Module.
type Module struct {
	// No Examples: 04
	No string `json:"no"`

	// Title Examples: DevOps
	Title  string  `json:"title"`
	Tracks []Track `json:"tracks"`
}

// OpsDay defines model for OpsDay.
type OpsDay struct {
	// D Examples: 2026-06-12
	D openapi_types.Date `json:"d"`

	// DownSec Examples: 2520
	DownSec int `json:"downSec"`

	// IncidentId Set when the day carries a notch.
	//
	// Examples: INC-001
	IncidentId *string `json:"incidentId,omitempty"`

	// State `nodata` is the important one. A day without a measurement is `nodata`, never
	// `ok` — an empty grid is more honest than a full one that was invented.
	State DayState `json:"state"`
}

// OpsSummary defines model for OpsSummary.
type OpsSummary struct {
	// ErrorRate Share of 5xx responses, as a fraction between 0 and 1.
	//
	// Examples: 0.0007
	ErrorRate  *float64 `json:"errorRate"`
	LastDeploy *Deploy  `json:"lastDeploy"`

	// MeasuredAt When these values were taken. A value without its age cannot be told apart
	// from a fresh one, and the site shows stale numbers *with* their age rather
	// than pretending.
	MeasuredAt *time.Time `json:"measuredAt"`

	// P95Ms 95th percentile latency, measured at the reverse proxy.
	//
	// Examples: 142
	P95Ms        *float64 `json:"p95Ms"`
	SystemsLive  int      `json:"systemsLive"`
	SystemsTotal int      `json:"systemsTotal"`

	// Uptime90d Share of time the system answered, as a percentage. The name says 90 for
	// historical reasons; the window is **91 days** (13 × 7) everywhere else in
	// this contract and on the site.
	//
	//
	// Examples: 99.64
	Uptime90d *float64 `json:"uptime90d"`
}

// ProbeReport defines model for ProbeReport.
type ProbeReport struct {
	At        time.Time `json:"at"`
	LatencyMs *int      `json:"latencyMs,omitempty"`

	// Reason Set when `up` is false.
	//
	// Examples: connect timeout
	Reason *string `json:"reason,omitempty"`
	Up     bool    `json:"up"`
}

// Problem RFC 9457 Problem Details, used for **every** error response including
// `/api/contact`. Two error shapes in one API is the kind of special case
// somebody misses later.
//
// `detail` never carries a stack trace or a database message — those go to the
// log, keyed by `requestId`.
type Problem struct {
	// Detail What went wrong with *this* request. Safe to show a visitor.
	Detail *string `json:"detail,omitempty"`

	// Instance The path that produced it.
	//
	// Examples: /api/contact
	Instance *string `json:"instance,omitempty"`

	// InvalidParams Present on `400` only, one entry per rejected field.
	InvalidParams *[]InvalidParam `json:"invalidParams,omitempty"`

	// RequestId Also sent as the `X-Request-Id` response header. Quoting it in a bug
	// report finds every log line from both services.
	RequestId *string `json:"requestId,omitempty"`

	// Status Examples: 400
	Status int `json:"status"`

	// Title Short, human-readable, stable for a given `type`.
	//
	// Examples: Validation failed
	Title string `json:"title"`

	// Type A URI under `https://timseil.dev/problems/`.
	//
	// Examples: https://timseil.dev/problems/validation-failed
	Type string `json:"type"`
}

// Source How the code can be reached. This is a separate axis from `state`: a system can
// be open and not running, or running and closed. Squeezing both into one field
// is the classic modelling mistake — you notice it when the first NDA client
// arrives.
type Source struct {
	union json.RawMessage
}

// SourcePrivate defines model for SourcePrivate.
type SourcePrivate struct {
	Access SourcePrivateAccess `json:"access"`

	// Reason Why a closed system is closed. `<> PRIVATE · NDA` is an honest statement;
	// `<> PRIVATE` with no reason would be an excuse, so the contract requires one.
	Reason SourceReason `json:"reason"`
}

// SourcePrivateAccess defines model for SourcePrivate.Access.
type SourcePrivateAccess string

// SourcePublic defines model for SourcePublic.
type SourcePublic struct {
	Access SourcePublicAccess `json:"access"`

	// Url Examples: https://github.com/G1NG4R/timseil-dev
	Url string `json:"url"`
}

// SourcePublicAccess defines model for SourcePublic.Access.
type SourcePublicAccess string

// SourceReason Why a closed system is closed. `<> PRIVATE · NDA` is an honest statement;
// `<> PRIVATE` with no reason would be an excuse, so the contract requires one.
type SourceReason string

// System defines model for System.
type System struct {
	// Metrics Every field is nullable and that is the point. `null` renders as `— NO DATA`;
	// `0` is a real measurement and must never stand in for a missing one.
	//
	// Only systems in state `live` carry values here.
	Metrics Metrics `json:"metrics"`

	// Name Examples: timseil.dev
	Name string `json:"name"`

	// Slug Examples: timseil-dev
	Slug string `json:"slug"`

	// Source How the code can be reached. This is a separate axis from `state`: a system can
	// be open and not running, or running and closed. Squeezing both into one field
	// is the classic modelling mistake — you notice it when the first NDA client
	// arrives.
	Source Source `json:"source"`

	// Stack Curated in `stack.yaml`, versions checked against `go.mod`,
	// `package.json` and `compose.yaml` in CI. Nobody types a version number
	// into a page again.
	//
	//
	// Examples: ["Next.js 16.3","Go 1.26","PostgreSQL 18.6"]
	Stack []string `json:"stack"`

	// State What the system *does*. Independent of who may read its code.
	State SystemState `json:"state"`

	// SystemNo Two-digit display number, zero padded.
	//
	// Examples: 02
	SystemNo string `json:"systemNo"`
}

// SystemDetail defines model for SystemDetail.
type SystemDetail struct {
	// Days Absent unless `state` is `live`.
	Days *[]OpsDay `json:"days,omitempty"`

	// Deploys Absent unless `state` is `live`.
	Deploys     *[]Deploy `json:"deploys,omitempty"`
	GeneratedAt time.Time `json:"generatedAt"`

	// Incidents Absent unless `state` is `live`.
	Incidents *[]Incident `json:"incidents,omitempty"`

	// Metrics Every field is nullable and that is the point. `null` renders as `— NO DATA`;
	// `0` is a real measurement and must never stand in for a missing one.
	//
	// Only systems in state `live` carry values here.
	Metrics Metrics `json:"metrics"`

	// Name Examples: timseil.dev
	Name string `json:"name"`

	// Slug Examples: timseil-dev
	Slug string `json:"slug"`

	// Source How the code can be reached. This is a separate axis from `state`: a system can
	// be open and not running, or running and closed. Squeezing both into one field
	// is the classic modelling mistake — you notice it when the first NDA client
	// arrives.
	Source Source `json:"source"`

	// Stack Curated in `stack.yaml`, versions checked against `go.mod`,
	// `package.json` and `compose.yaml` in CI. Nobody types a version number
	// into a page again.
	//
	//
	// Examples: ["Next.js 16.3","Go 1.26","PostgreSQL 18.6"]
	Stack []string `json:"stack"`

	// State What the system *does*. Independent of who may read its code.
	State SystemState `json:"state"`

	// SystemNo Two-digit display number, zero padded.
	//
	// Examples: 02
	SystemNo string `json:"systemNo"`

	// Window How many days `days` covers.
	//
	// Examples: 91
	Window int `json:"window"`
}

// SystemList defines model for SystemList.
type SystemList struct {
	GeneratedAt time.Time `json:"generatedAt"`
	Systems     []System  `json:"systems"`
}

// SystemState What the system *does*. Independent of who may read its code.
type SystemState string

// Track defines model for Track.
type Track struct {
	// Evidence Empty means no system yet — self-study, and said so plainly.
	Evidence []Evidence `json:"evidence"`

	// Name Examples: CI/CD (GitHub Actions)
	Name string `json:"name"`

	// Note Set only when `evidence` is empty.
	//
	// Examples: self-study
	Note *string `json:"note,omitempty"`

	// State Derived from evidence, never stored. `core` needs two live systems: building
	// something once means getting it to run once; running it twice means having met
	// the cases that were luck the first time.
	State TrackState `json:"state"`
}

// TrackState Derived from evidence, never stored. `core` needs two live systems: building
// something once means getting it to run once; running it twice means having met
// the cases that were luck the first time.
type TrackState string

// Training defines model for Training.
type Training struct {
	// EvidenceSystems Distinct systems backing at least one track.
	//
	// Examples: 1
	EvidenceSystems int       `json:"evidenceSystems"`
	GeneratedAt     time.Time `json:"generatedAt"`
	Modules         []Module  `json:"modules"`

	// TrackCount Examples: 22
	TrackCount int `json:"trackCount"`
}

// IfNoneMatch defines model for IfNoneMatch.
type IfNoneMatch = string

// Slug defines model for Slug.
type Slug = string

// Window defines model for Window.
type Window int

// BadGateway RFC 9457 Problem Details, used for **every** error response including
// `/api/contact`. Two error shapes in one API is the kind of special case
// somebody misses later.
//
// `detail` never carries a stack trace or a database message — those go to the
// log, keyed by `requestId`.
type BadGateway = Problem

// BadRequest RFC 9457 Problem Details, used for **every** error response including
// `/api/contact`. Two error shapes in one API is the kind of special case
// somebody misses later.
//
// `detail` never carries a stack trace or a database message — those go to the
// log, keyed by `requestId`.
type BadRequest = Problem

// BadgeOK The payload Shields.io expects from an endpoint badge. It is a foreign schema,
// but it belongs in this contract — three routes that exist and are documented
// nowhere would fail the router parity check.
type BadgeOK = Badge

// InternalError RFC 9457 Problem Details, used for **every** error response including
// `/api/contact`. Two error shapes in one API is the kind of special case
// somebody misses later.
//
// `detail` never carries a stack trace or a database message — those go to the
// log, keyed by `requestId`.
type InternalError = Problem

// NotFound RFC 9457 Problem Details, used for **every** error response including
// `/api/contact`. Two error shapes in one API is the kind of special case
// somebody misses later.
//
// `detail` never carries a stack trace or a database message — those go to the
// log, keyed by `requestId`.
type NotFound = Problem

// TooManyRequests RFC 9457 Problem Details, used for **every** error response including
// `/api/contact`. Two error shapes in one API is the kind of special case
// somebody misses later.
//
// `detail` never carries a stack trace or a database message — those go to the
// log, keyed by `requestId`.
type TooManyRequests = Problem

// Unauthorized RFC 9457 Problem Details, used for **every** error response including
// `/api/contact`. Two error shapes in one API is the kind of special case
// somebody misses later.
//
// `detail` never carries a stack trace or a database message — those go to the
// log, keyed by `requestId`.
type Unauthorized = Problem

// GetContributionsParams defines parameters for GetContributions.
type GetContributionsParams struct {
	// IfNoneMatch The `ETag` of a previously fetched representation.
	IfNoneMatch *IfNoneMatch `json:"If-None-Match,omitempty"`
}

// GetHealthParams defines parameters for GetHealth.
type GetHealthParams struct {
	// IfNoneMatch The `ETag` of a previously fetched representation.
	IfNoneMatch *IfNoneMatch `json:"If-None-Match,omitempty"`
}

// ListSystemsParams defines parameters for ListSystems.
type ListSystemsParams struct {
	// IfNoneMatch The `ETag` of a previously fetched representation.
	IfNoneMatch *IfNoneMatch `json:"If-None-Match,omitempty"`
}

// GetSystemParams defines parameters for GetSystem.
type GetSystemParams struct {
	// Window How many days of the operation grid to return. 91 is 13 × 7 — seven rows only
	// hold multiples of seven, and at 90 the last column would have a hole that
	// looks like a bug. 30 is the homepage strip, 182 is the wide view.
	Window *GetSystemParamsWindow `form:"window,omitempty" json:"window,omitempty"`

	// IfNoneMatch The `ETag` of a previously fetched representation.
	IfNoneMatch *IfNoneMatch `json:"If-None-Match,omitempty"`
}

// GetSystemParamsWindow defines parameters for GetSystem.
type GetSystemParamsWindow int

// GetTrainingParams defines parameters for GetTraining.
type GetTrainingParams struct {
	// IfNoneMatch The `ETag` of a previously fetched representation.
	IfNoneMatch *IfNoneMatch `json:"If-None-Match,omitempty"`
}

// SubmitContactJSONRequestBody defines body for SubmitContact for application/json ContentType.
type SubmitContactJSONRequestBody = ContactRequest

// ReportDeployJSONRequestBody defines body for ReportDeploy for application/json ContentType.
type ReportDeployJSONRequestBody = DeployReport

// ReportProbeJSONRequestBody defines body for ReportProbe for application/json ContentType.
type ReportProbeJSONRequestBody = ProbeReport

// AsSourcePublic returns the union data inside the Source as a SourcePublic
func (t Source) AsSourcePublic() (SourcePublic, error) {
	var body SourcePublic
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSourcePublic overwrites any union data inside the Source as the provided SourcePublic
func (t *Source) FromSourcePublic(v SourcePublic) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"access":"public"}`))
	t.union = b
	return err
}

// MergeSourcePublic performs a merge with any union data inside the Source, using the provided SourcePublic
func (t *Source) MergeSourcePublic(v SourcePublic) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"access":"public"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSourcePrivate returns the union data inside the Source as a SourcePrivate
func (t Source) AsSourcePrivate() (SourcePrivate, error) {
	var body SourcePrivate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSourcePrivate overwrites any union data inside the Source as the provided SourcePrivate
func (t *Source) FromSourcePrivate(v SourcePrivate) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"access":"private"}`))
	t.union = b
	return err
}

// MergeSourcePrivate performs a merge with any union data inside the Source, using the provided SourcePrivate
func (t *Source) MergeSourcePrivate(v SourcePrivate) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"access":"private"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Source) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"access"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Source) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "private":
		return t.AsSourcePrivate()
	case "public":
		return t.AsSourcePublic()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Source) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Source) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetSystemsBadge Shields.io endpoint badge — live systems
	// (GET /api/badge/systems)
	GetSystemsBadge(w http.ResponseWriter, r *http.Request)
	// GetUptimeBadge Shields.io endpoint badge — uptime
	// (GET /api/badge/uptime)
	GetUptimeBadge(w http.ResponseWriter, r *http.Request)
	// GetVersionBadge Shields.io endpoint badge — deployed version
	// (GET /api/badge/version)
	GetVersionBadge(w http.ResponseWriter, r *http.Request)
	// SubmitContact Send a message
	// (POST /api/contact)
	SubmitContact(w http.ResponseWriter, r *http.Request)
	// GetContributions The GitHub contribution calendar, fetched server-side
	// (GET /api/contributions)
	GetContributions(w http.ResponseWriter, r *http.Request, params GetContributionsParams)
	// GetDocs This contract, rendered
	// (GET /api/docs)
	GetDocs(w http.ResponseWriter, r *http.Request)
	// GetDocsAsset The renderer that /api/docs loads
	// (GET /api/docs/scalar.js)
	GetDocsAsset(w http.ResponseWriter, r *http.Request)
	// GetHealth Liveness, build identity and operational metrics
	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request, params GetHealthParams)
	// ReportDeploy The pipeline reports its own duration
	// (POST /api/internal/deploy)
	ReportDeploy(w http.ResponseWriter, r *http.Request)
	// ReportProbe An external prober reports that the host answered
	// (POST /api/internal/probe)
	ReportProbe(w http.ResponseWriter, r *http.Request)
	// GetOpenapiDocument This contract, raw
	// (GET /api/openapi.yaml)
	GetOpenapiDocument(w http.ResponseWriter, r *http.Request)
	// ListSystems Every tracked system with its state, its source and its metrics
	// (GET /api/systems)
	ListSystems(w http.ResponseWriter, r *http.Request, params ListSystemsParams)
	// GetSystem One system with its operation grid, incidents and deploys
	// (GET /api/systems/{slug})
	GetSystem(w http.ResponseWriter, r *http.Request, slug Slug, params GetSystemParams)
	// GetTraining Modules, tracks and the systems that prove them
	// (GET /api/training)
	GetTraining(w http.ResponseWriter, r *http.Request, params GetTrainingParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetSystemsBadge operation middleware
func (siw *ServerInterfaceWrapper) GetSystemsBadge(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemsBadge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUptimeBadge operation middleware
func (siw *ServerInterfaceWrapper) GetUptimeBadge(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUptimeBadge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersionBadge operation middleware
func (siw *ServerInterfaceWrapper) GetVersionBadge(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersionBadge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitContact operation middleware
func (siw *ServerInterfaceWrapper) SubmitContact(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitContact(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetContributions operation middleware
func (siw *ServerInterfaceWrapper) GetContributions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetContributionsParams

	headers := r.Header

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch IfNoneMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContributions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocs operation middleware
func (siw *ServerInterfaceWrapper) GetDocs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocsAsset operation middleware
func (siw *ServerInterfaceWrapper) GetDocsAsset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocsAsset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHealthParams

	headers := r.Header

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch IfNoneMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportDeploy operation middleware
func (siw *ServerInterfaceWrapper) ReportDeploy(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportDeploy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportProbe operation middleware
func (siw *ServerInterfaceWrapper) ReportProbe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportProbe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenapiDocument operation middleware
func (siw *ServerInterfaceWrapper) GetOpenapiDocument(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenapiDocument(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSystems operation middleware
func (siw *ServerInterfaceWrapper) ListSystems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSystemsParams

	headers := r.Header

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch IfNoneMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSystems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystem operation middleware
func (siw *ServerInterfaceWrapper) GetSystem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSystemParams

	// ------------- Optional query parameter "window" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "window", r.URL.Query(), &params.Window, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "window"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "window", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch IfNoneMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystem(w, r, slug, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTraining operation middleware
func (siw *ServerInterfaceWrapper) GetTraining(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrainingParams

	headers := r.Header

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch IfNoneMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTraining(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/systems", wrapper.ListSystems)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/systems/{slug}", wrapper.GetSystem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/training", wrapper.GetTraining)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/contributions", wrapper.GetContributions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/contact", wrapper.SubmitContact)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/docs", wrapper.GetDocs)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/docs/scalar.js", wrapper.GetDocsAsset)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/openapi.yaml", wrapper.GetOpenapiDocument)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/badge/uptime", wrapper.GetUptimeBadge)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/badge/version", wrapper.GetVersionBadge)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/badge/systems", wrapper.GetSystemsBadge)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/internal/probe", wrapper.ReportProbe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/internal/deploy", wrapper.ReportDeploy)

	return m
}

type AcceptedNoContentResponseHeaders struct {
	CacheControl *string
}
type AcceptedNoContentResponse struct {
	Headers AcceptedNoContentResponseHeaders
}

type BadGatewayApplicationProblemPlusJSONResponse Problem

type BadRequestApplicationProblemPlusJSONResponse Problem

type BadgeOKResponseHeaders struct {
	CacheControl *string
}
type BadgeOKJSONResponse struct {
	Body Badge

	Headers BadgeOKResponseHeaders
}

type InternalErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type NotModifiedResponseHeaders struct {
	ETag *string
}
type NotModifiedResponse struct {
	Headers NotModifiedResponseHeaders
}

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type GetSystemsBadgeRequestObject struct {
}

type GetSystemsBadgeResponseObject interface {
	VisitGetSystemsBadgeResponse(w http.ResponseWriter) error
}

type GetSystemsBadge200JSONResponse struct{ BadgeOKJSONResponse }

func (response GetSystemsBadge200JSONResponse) VisitGetSystemsBadgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSystemsBadge429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetSystemsBadge429ApplicationProblemPlusJSONResponse) VisitGetSystemsBadgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetUptimeBadgeRequestObject struct {
}

type GetUptimeBadgeResponseObject interface {
	VisitGetUptimeBadgeResponse(w http.ResponseWriter) error
}

type GetUptimeBadge200JSONResponse struct{ BadgeOKJSONResponse }

func (response GetUptimeBadge200JSONResponse) VisitGetUptimeBadgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUptimeBadge429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetUptimeBadge429ApplicationProblemPlusJSONResponse) VisitGetUptimeBadgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionBadgeRequestObject struct {
}

type GetVersionBadgeResponseObject interface {
	VisitGetVersionBadgeResponse(w http.ResponseWriter) error
}

type GetVersionBadge200JSONResponse struct{ BadgeOKJSONResponse }

func (response GetVersionBadge200JSONResponse) VisitGetVersionBadgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionBadge429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetVersionBadge429ApplicationProblemPlusJSONResponse) VisitGetVersionBadgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitContactRequestObject struct {
	Body *SubmitContactJSONRequestBody
}

type SubmitContactResponseObject interface {
	VisitSubmitContactResponse(w http.ResponseWriter) error
}

type SubmitContact202ResponseHeaders struct {
	CacheControl *string
}

type SubmitContact202JSONResponse struct {
	Body    ContactAccepted
	Headers SubmitContact202ResponseHeaders
}

func (response SubmitContact202JSONResponse) VisitSubmitContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitContact400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response SubmitContact400ApplicationProblemPlusJSONResponse) VisitSubmitContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitContact429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response SubmitContact429ApplicationProblemPlusJSONResponse) VisitSubmitContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitContact500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response SubmitContact500ApplicationProblemPlusJSONResponse) VisitSubmitContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitContact502ApplicationProblemPlusJSONResponse struct {
	BadGatewayApplicationProblemPlusJSONResponse
}

func (response SubmitContact502ApplicationProblemPlusJSONResponse) VisitSubmitContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetContributionsRequestObject struct {
	Params GetContributionsParams
}

type GetContributionsResponseObject interface {
	VisitGetContributionsResponse(w http.ResponseWriter) error
}

type GetContributions200ResponseHeaders struct {
	CacheControl *string
	ETag         *string
}

type GetContributions200JSONResponse struct {
	Body    Contributions
	Headers GetContributions200ResponseHeaders
}

func (response GetContributions200JSONResponse) VisitGetContributionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetContributions304Response = NotModifiedResponse

func (response GetContributions304Response) VisitGetContributionsResponse(w http.ResponseWriter) error {
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(304)
	return nil
}

type GetContributions429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetContributions429ApplicationProblemPlusJSONResponse) VisitGetContributionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetContributions500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetContributions500ApplicationProblemPlusJSONResponse) VisitGetContributionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetContributions502ApplicationProblemPlusJSONResponse struct {
	BadGatewayApplicationProblemPlusJSONResponse
}

func (response GetContributions502ApplicationProblemPlusJSONResponse) VisitGetContributionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocsRequestObject struct {
}

type GetDocsResponseObject interface {
	VisitGetDocsResponse(w http.ResponseWriter) error
}

type GetDocs200ResponseHeaders struct {
	CacheControl *string
}

type GetDocs200TexthtmlResponse struct {
	Body          io.Reader
	Headers       GetDocs200ResponseHeaders
	ContentLength int64
}

func (response GetDocs200TexthtmlResponse) VisitGetDocsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetDocs429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetDocs429ApplicationProblemPlusJSONResponse) VisitGetDocsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocsAssetRequestObject struct {
}

type GetDocsAssetResponseObject interface {
	VisitGetDocsAssetResponse(w http.ResponseWriter) error
}

type GetDocsAsset200ResponseHeaders struct {
	CacheControl *string
	ETag         *string
}

type GetDocsAsset200TextjavascriptResponse struct {
	Body          io.Reader
	Headers       GetDocsAsset200ResponseHeaders
	ContentLength int64
}

func (response GetDocsAsset200TextjavascriptResponse) VisitGetDocsAssetResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/javascript")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetDocsAsset429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetDocsAsset429ApplicationProblemPlusJSONResponse) VisitGetDocsAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
	Params GetHealthParams
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200ResponseHeaders struct {
	CacheControl *string
	ETag         *string
}

type GetHealth200JSONResponse struct {
	Body    Health
	Headers GetHealth200ResponseHeaders
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth304Response = NotModifiedResponse

func (response GetHealth304Response) VisitGetHealthResponse(w http.ResponseWriter) error {
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(304)
	return nil
}

type GetHealth429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetHealth429ApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetHealth500ApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReportDeployRequestObject struct {
	Body *ReportDeployJSONRequestBody
}

type ReportDeployResponseObject interface {
	VisitReportDeployResponse(w http.ResponseWriter) error
}

type ReportDeploy204Response = AcceptedNoContentResponse

func (response ReportDeploy204Response) VisitReportDeployResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(204)
	return nil
}

type ReportDeploy400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ReportDeploy400ApplicationProblemPlusJSONResponse) VisitReportDeployResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReportDeploy401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ReportDeploy401ApplicationProblemPlusJSONResponse) VisitReportDeployResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReportDeploy429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response ReportDeploy429ApplicationProblemPlusJSONResponse) VisitReportDeployResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ReportDeploy500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ReportDeploy500ApplicationProblemPlusJSONResponse) VisitReportDeployResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReportProbeRequestObject struct {
	Body *ReportProbeJSONRequestBody
}

type ReportProbeResponseObject interface {
	VisitReportProbeResponse(w http.ResponseWriter) error
}

type ReportProbe204Response = AcceptedNoContentResponse

func (response ReportProbe204Response) VisitReportProbeResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(204)
	return nil
}

type ReportProbe400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ReportProbe400ApplicationProblemPlusJSONResponse) VisitReportProbeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReportProbe401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ReportProbe401ApplicationProblemPlusJSONResponse) VisitReportProbeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReportProbe429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response ReportProbe429ApplicationProblemPlusJSONResponse) VisitReportProbeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ReportProbe500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ReportProbe500ApplicationProblemPlusJSONResponse) VisitReportProbeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetOpenapiDocumentRequestObject struct {
}

type GetOpenapiDocumentResponseObject interface {
	VisitGetOpenapiDocumentResponse(w http.ResponseWriter) error
}

type GetOpenapiDocument200ResponseHeaders struct {
	CacheControl *string
	ETag         *string
}

type GetOpenapiDocument200ApplicationyamlResponse struct {
	Body          io.Reader
	Headers       GetOpenapiDocument200ResponseHeaders
	ContentLength int64
}

func (response GetOpenapiDocument200ApplicationyamlResponse) VisitGetOpenapiDocumentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetOpenapiDocument429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetOpenapiDocument429ApplicationProblemPlusJSONResponse) VisitGetOpenapiDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListSystemsRequestObject struct {
	Params ListSystemsParams
}

type ListSystemsResponseObject interface {
	VisitListSystemsResponse(w http.ResponseWriter) error
}

type ListSystems200ResponseHeaders struct {
	CacheControl *string
	ETag         *string
}

type ListSystems200JSONResponse struct {
	Body    SystemList
	Headers ListSystems200ResponseHeaders
}

func (response ListSystems200JSONResponse) VisitListSystemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSystems304Response = NotModifiedResponse

func (response ListSystems304Response) VisitListSystemsResponse(w http.ResponseWriter) error {
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(304)
	return nil
}

type ListSystems429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response ListSystems429ApplicationProblemPlusJSONResponse) VisitListSystemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListSystems500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListSystems500ApplicationProblemPlusJSONResponse) VisitListSystemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetSystemRequestObject struct {
	Slug   Slug `json:"slug"`
	Params GetSystemParams
}

type GetSystemResponseObject interface {
	VisitGetSystemResponse(w http.ResponseWriter) error
}

type GetSystem200ResponseHeaders struct {
	CacheControl *string
	ETag         *string
}

type GetSystem200JSONResponse struct {
	Body    SystemDetail
	Headers GetSystem200ResponseHeaders
}

func (response GetSystem200JSONResponse) VisitGetSystemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSystem304Response = NotModifiedResponse

func (response GetSystem304Response) VisitGetSystemResponse(w http.ResponseWriter) error {
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(304)
	return nil
}

type GetSystem404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetSystem404ApplicationProblemPlusJSONResponse) VisitGetSystemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSystem429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetSystem429ApplicationProblemPlusJSONResponse) VisitGetSystemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetSystem500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetSystem500ApplicationProblemPlusJSONResponse) VisitGetSystemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetTrainingRequestObject struct {
	Params GetTrainingParams
}

type GetTrainingResponseObject interface {
	VisitGetTrainingResponse(w http.ResponseWriter) error
}

type GetTraining200ResponseHeaders struct {
	CacheControl *string
	ETag         *string
}

type GetTraining200JSONResponse struct {
	Body    Training
	Headers GetTraining200ResponseHeaders
}

func (response GetTraining200JSONResponse) VisitGetTrainingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTraining304Response = NotModifiedResponse

func (response GetTraining304Response) VisitGetTrainingResponse(w http.ResponseWriter) error {
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(304)
	return nil
}

type GetTraining429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetTraining429ApplicationProblemPlusJSONResponse) VisitGetTrainingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetTraining500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetTraining500ApplicationProblemPlusJSONResponse) VisitGetTrainingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetSystemsBadge Shields.io endpoint badge — live systems
	// (GET /api/badge/systems)
	GetSystemsBadge(ctx context.Context, request GetSystemsBadgeRequestObject) (GetSystemsBadgeResponseObject, error)
	// GetUptimeBadge Shields.io endpoint badge — uptime
	// (GET /api/badge/uptime)
	GetUptimeBadge(ctx context.Context, request GetUptimeBadgeRequestObject) (GetUptimeBadgeResponseObject, error)
	// GetVersionBadge Shields.io endpoint badge — deployed version
	// (GET /api/badge/version)
	GetVersionBadge(ctx context.Context, request GetVersionBadgeRequestObject) (GetVersionBadgeResponseObject, error)
	// SubmitContact Send a message
	// (POST /api/contact)
	SubmitContact(ctx context.Context, request SubmitContactRequestObject) (SubmitContactResponseObject, error)
	// GetContributions The GitHub contribution calendar, fetched server-side
	// (GET /api/contributions)
	GetContributions(ctx context.Context, request GetContributionsRequestObject) (GetContributionsResponseObject, error)
	// GetDocs This contract, rendered
	// (GET /api/docs)
	GetDocs(ctx context.Context, request GetDocsRequestObject) (GetDocsResponseObject, error)
	// GetDocsAsset The renderer that /api/docs loads
	// (GET /api/docs/scalar.js)
	GetDocsAsset(ctx context.Context, request GetDocsAssetRequestObject) (GetDocsAssetResponseObject, error)
	// GetHealth Liveness, build identity and operational metrics
	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ReportDeploy The pipeline reports its own duration
	// (POST /api/internal/deploy)
	ReportDeploy(ctx context.Context, request ReportDeployRequestObject) (ReportDeployResponseObject, error)
	// ReportProbe An external prober reports that the host answered
	// (POST /api/internal/probe)
	ReportProbe(ctx context.Context, request ReportProbeRequestObject) (ReportProbeResponseObject, error)
	// GetOpenapiDocument This contract, raw
	// (GET /api/openapi.yaml)
	GetOpenapiDocument(ctx context.Context, request GetOpenapiDocumentRequestObject) (GetOpenapiDocumentResponseObject, error)
	// ListSystems Every tracked system with its state, its source and its metrics
	// (GET /api/systems)
	ListSystems(ctx context.Context, request ListSystemsRequestObject) (ListSystemsResponseObject, error)
	// GetSystem One system with its operation grid, incidents and deploys
	// (GET /api/systems/{slug})
	GetSystem(ctx context.Context, request GetSystemRequestObject) (GetSystemResponseObject, error)
	// GetTraining Modules, tracks and the systems that prove them
	// (GET /api/training)
	GetTraining(ctx context.Context, request GetTrainingRequestObject) (GetTrainingResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetSystemsBadge operation middleware
func (sh *strictHandler) GetSystemsBadge(w http.ResponseWriter, r *http.Request) {
	var request GetSystemsBadgeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystemsBadge(ctx, request.(GetSystemsBadgeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystemsBadge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSystemsBadgeResponseObject); ok {
		if err := validResponse.VisitGetSystemsBadgeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUptimeBadge operation middleware
func (sh *strictHandler) GetUptimeBadge(w http.ResponseWriter, r *http.Request) {
	var request GetUptimeBadgeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUptimeBadge(ctx, request.(GetUptimeBadgeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUptimeBadge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUptimeBadgeResponseObject); ok {
		if err := validResponse.VisitGetUptimeBadgeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersionBadge operation middleware
func (sh *strictHandler) GetVersionBadge(w http.ResponseWriter, r *http.Request) {
	var request GetVersionBadgeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersionBadge(ctx, request.(GetVersionBadgeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersionBadge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionBadgeResponseObject); ok {
		if err := validResponse.VisitGetVersionBadgeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitContact operation middleware
func (sh *strictHandler) SubmitContact(w http.ResponseWriter, r *http.Request) {
	var request SubmitContactRequestObject

	var body SubmitContactJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitContact(ctx, request.(SubmitContactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitContact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitContactResponseObject); ok {
		if err := validResponse.VisitSubmitContactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetContributions operation middleware
func (sh *strictHandler) GetContributions(w http.ResponseWriter, r *http.Request, params GetContributionsParams) {
	var request GetContributionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetContributions(ctx, request.(GetContributionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetContributions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetContributionsResponseObject); ok {
		if err := validResponse.VisitGetContributionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDocs operation middleware
func (sh *strictHandler) GetDocs(w http.ResponseWriter, r *http.Request) {
	var request GetDocsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocs(ctx, request.(GetDocsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocsResponseObject); ok {
		if err := validResponse.VisitGetDocsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDocsAsset operation middleware
func (sh *strictHandler) GetDocsAsset(w http.ResponseWriter, r *http.Request) {
	var request GetDocsAssetRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocsAsset(ctx, request.(GetDocsAssetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocsAsset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocsAssetResponseObject); ok {
		if err := validResponse.VisitGetDocsAssetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request, params GetHealthParams) {
	var request GetHealthRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReportDeploy operation middleware
func (sh *strictHandler) ReportDeploy(w http.ResponseWriter, r *http.Request) {
	var request ReportDeployRequestObject

	var body ReportDeployJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReportDeploy(ctx, request.(ReportDeployRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReportDeploy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReportDeployResponseObject); ok {
		if err := validResponse.VisitReportDeployResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReportProbe operation middleware
func (sh *strictHandler) ReportProbe(w http.ResponseWriter, r *http.Request) {
	var request ReportProbeRequestObject

	var body ReportProbeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReportProbe(ctx, request.(ReportProbeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReportProbe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReportProbeResponseObject); ok {
		if err := validResponse.VisitReportProbeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOpenapiDocument operation middleware
func (sh *strictHandler) GetOpenapiDocument(w http.ResponseWriter, r *http.Request) {
	var request GetOpenapiDocumentRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenapiDocument(ctx, request.(GetOpenapiDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenapiDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOpenapiDocumentResponseObject); ok {
		if err := validResponse.VisitGetOpenapiDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSystems operation middleware
func (sh *strictHandler) ListSystems(w http.ResponseWriter, r *http.Request, params ListSystemsParams) {
	var request ListSystemsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSystems(ctx, request.(ListSystemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSystems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSystemsResponseObject); ok {
		if err := validResponse.VisitListSystemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSystem operation middleware
func (sh *strictHandler) GetSystem(w http.ResponseWriter, r *http.Request, slug Slug, params GetSystemParams) {
	var request GetSystemRequestObject

	request.Slug = slug
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystem(ctx, request.(GetSystemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSystemResponseObject); ok {
		if err := validResponse.VisitGetSystemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTraining operation middleware
func (sh *strictHandler) GetTraining(w http.ResponseWriter, r *http.Request, params GetTrainingParams) {
	var request GetTrainingRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTraining(ctx, request.(GetTrainingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTraining")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTrainingResponseObject); ok {
		if err := validResponse.VisitGetTrainingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
