// The web linter. Two layers, and the second one is the one E2 added.
//
// The Next.js layers stay first and unmodified: core-web-vitals carries the
// rules that catch a page shipping something it should not, and the typescript
// layer wires the parser. What follows is typescript-eslint's strict,
// type-aware set, which is a different kind of check — it reads the types
// rather than the syntax, so it can see a floating promise or a value narrowed
// to `any` on the way through a boundary.
//
// **It measures almost nothing today, on purpose.** web/ is layout.tsx and
// page.tsx; stage G is what fills it. Turning these rules on now costs one
// pull request and no fixes, and turning them on later costs one pull request
// and a page of them. The rules are here to meet the code, not the other way
// round.
//
// Build plan E2, ADR 0031.

import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import tseslint from "typescript-eslint";

// Anything a browser is allowed to see. The prefix is the whole rule: NEXT_PUBLIC_
// means Next.js inlines the value into the client bundle at build time, so a
// name added here is a decision to publish whatever it holds.
//
// Empty, and it should stay empty for as long as it can. Nothing in this
// application needs a build-time constant in the browser today; ADR 0004 made
// the read API public, so the browser asks the API instead of being told
// things in advance.
const PUBLIC_ENV = [];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // Type-aware, so it needs to know which tsconfig owns a file. projectService
  // asks TypeScript rather than being handed a glob, which is what keeps this
  // working when stage G adds directories nobody listed here.
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  {
    rules: {
      // The build plan's rule, as a lint rule (chapter 11.4): "Nichts mit
      // NEXT_PUBLIC_-Präfix, das geheim ist."
      //
      // This half catches the READ — code reaching for a public variable that
      // nobody has declared public. The other half, which catches a secret
      // being DEFINED behind the prefix in an .env or compose file, is
      // check-env.sh and belongs to E2b: the files it reads are not JavaScript
      // and ESLint would never see them.
      //
      // Written as a selector rather than a plugin because it is one shape and
      // one repository. `process.env.NEXT_PUBLIC_ANYTHING` is refused unless
      // ANYTHING is in PUBLIC_ENV above, which is currently nothing at all.
      "no-restricted-syntax": [
        "error",
        {
          selector: [
            "MemberExpression",
            "[object.object.name='process']",
            "[object.property.name='env']",
            "[property.name=/^NEXT_PUBLIC_/]",
            PUBLIC_ENV.map((name) => `[property.name!='${name}']`).join(""),
          ].join(""),
          message:
            "NEXT_PUBLIC_ ships this value to the browser. Add the name to " +
            "PUBLIC_ENV in eslint.config.mjs if that is intended, and make " +
            "sure it is not a secret — the prefix cannot be taken back once " +
            "a build has gone out.",
        },
      ],
    },
  },

  // Unit tests, and one rule that is wrong about them.
  //
  // `describe` and `it` from node:test return a promise so that a runner CAN
  // await a suite. A test file is not that runner — the runner is the `node
  // --test` process, which awaits them itself — so every call here is a
  // deliberate floating promise, and there are as many of them as there are
  // tests. Writing `void` in front of eighty calls would be noise that teaches a
  // reader nothing; turning the rule off for this one file shape says the same
  // thing once.
  //
  // Nothing else is relaxed. The type-aware rules still read these files, which
  // is the point: a test that lies about a type is a test that passes for the
  // wrong reason.
  {
    files: ["**/*.test.ts"],
    rules: {
      "@typescript-eslint/no-floating-promises": "off",
    },
  },

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Type-aware rules need a file to be in a tsconfig, and this one is not.
    "eslint.config.mjs",
    // Generated by `make gen` from contract/openapi.yaml. Linting it would
    // argue with openapi-typescript about index signatures, and the only place
    // that argument could be settled is the generator — .golangci.yml refuses
    // generated Go for the same reason, and check-contract already proves this
    // file is not stale.
    "lib/api/schema.d.ts",
  ]),
]);

export default eslintConfig;
